'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
type Row={id:string;name:string}; type Teacher={id:string;first_name:string;last_name:string};
export default function Teachers(){const sb=createClient();const[teachers,setTeachers]=useState<Teacher[]>([]),[subjects,setSubjects]=useState<Row[]>([]),[programs,setPrograms]=useState<Row[]>([]),[assignments,setAssignments]=useState<any[]>([]),[form,setForm]=useState({teacher_id:'',subject_id:'',program_id:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
async function load(){setLoading(true);const org=(await sb.from('organizations').select('id').limit(1).maybeSingle()).data;if(!org){setLoading(false);return}const[{data:t},{data:s},{data:p}]=await Promise.all([sb.from('teachers').select('id,first_name,last_name').eq('organization_id',org.id).order('last_name'),sb.from('subjects').select('id,name').eq('organization_id',org.id).eq('is_active',true).order('name'),sb.from('programs').select('id,name').eq('organization_id',org.id).eq('is_active',true).order('name')]);setTeachers(t||[]);setSubjects(s||[]);setPrograms(p||[]);const{data:a}=await sb.from('teacher_subject_assignments').select('*').eq('organization_id',org.id).order('created_at',{ascending:false});setAssignments(a||[]);setLoading(false)}useEffect(()=>{load()},[]);
async function save(){if(!form.teacher_id||!form.subject_id||!form.program_id)return;setSaving(true);const org=(await sb.from('organizations').select('id').limit(1).maybeSingle()).data;if(org){const{error}=await sb.from('teacher_subject_assignments').insert({...form,organization_id:org.id});if(error)alert(error.message);else{setForm({teacher_id:'',subject_id:'',program_id:''});await load()}}setSaving(false)}
return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-5 py-8"><Link href="/admin" className="text-sm text-blue-600">← Administration</Link><header className="mt-5"><p className="text-sm font-black tracking-widest text-blue-600">CONIK • ENSEIGNANTS</p><h1 className="mt-1 text-3xl font-bold">Affectations</h1><p className="mt-2 text-sm text-slate-500">Associez un enseignant à une matière et une filière pour préparer la saisie des notes.</p></header><div className="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Nouvelle affectation</h2><div className="mt-4 space-y-3"><select value={form.teacher_id} onChange={e=>setForm({...form,teacher_id:e.target.value})} className="w-full rounded-xl border p-3 text-sm"><option value="">Enseignant</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.last_name} {t.first_name}</option>)}</select><select value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})} className="w-full rounded-xl border p-3 text-sm"><option value="">Matière</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={form.program_id} onChange={e=>setForm({...form,program_id:e.target.value})} className="w-full rounded-xl border p-3 text-sm"><option value="">Filière</option>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={saving} onClick={save} className="w-full rounded-xl bg-slate-900 p-3 text-sm font-semibold text-white disabled:opacity-40">{saving?'Enregistrement…':'Affecter'}</button></div></aside><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b bg-slate-50 px-5 py-4 font-semibold">Affectations existantes</div>{loading?<p className="p-8 text-sm text-slate-500">Chargement…</p>:assignments.length===0?<p className="p-8 text-sm text-slate-500">Aucune affectation pour le moment.</p>:<div className="divide-y">{assignments.map(a=><div key={a.id} className="px-5 py-4 text-sm"><span className="font-medium">{teachers.find(t=>t.id===a.teacher_id)?.last_name} {teachers.find(t=>t.id===a.teacher_id)?.first_name}</span><span className="mx-2 text-slate-400">•</span><span>{subjects.find(s=>s.id===a.subject_id)?.name||'Matière'}</span><span className="mx-2 text-slate-400">•</span><span>{programs.find(p=>p.id===a.program_id)?.name||'Filière'}</span></div>)}</div>}</section></div></div></main>}
