'use client'
import {useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type O={id:string;name:string;code?:string|null;is_current?:boolean}; type C={id:string;name:string;code:string|null;capacity:number|null;is_active:boolean;academic_year_id:string;level_id:string;program_id:string|null}; type A={id:string;class_group_id:string;enrollment_id:string;status:string}
export default function ClassManager({organizationId,initialClasses,years,levels,programs,initialAssignments}:{organizationId:string;initialClasses:C[];years:O[];levels:O[];programs:O[];initialAssignments:A[]}){
 const [classes,setClasses]=useState(initialClasses),[assignments,setAssignments]=useState(initialAssignments),[year,setYear]=useState(years.find(y=>y.is_current)?.id||years[0]?.id||''),[open,setOpen]=useState(false),[selected,setSelected]=useState<C|null>(null),[studentsOpen,setStudentsOpen]=useState<C|null>(null),[enrolled,setEnrolled]=useState<any[]>([]),[available,setAvailable]=useState<any[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({name:'',code:'',capacity:'',level_id:'',program_id:''})
 const lv=(id:string)=>levels.find(x=>x.id===id)?.name||'—'; const pr=(id:string|null)=>programs.find(x=>x.id===id)?.name||''
 const filtered=useMemo(()=>classes.filter(c=>c.academic_year_id===year),[classes,year]); const count=(id:string)=>assignments.filter(a=>a.class_group_id===id).length
 const loadStudents=async(c:C)=>{setStudentsOpen(c);const sb=createClient();const {data}=await sb.from('student_class_assignments').select('id,enrollment_id').eq('class_group_id',c.id).eq('status','active');const ids=(data||[]).map(x=>x.enrollment_id);const {data:es}=await sb.from('student_enrollments').select('id,enrollment_number,student_id,program_id,level_id').eq('organization_id',organizationId).eq('academic_year_id',c.academic_year_id).eq('status','active');const all=es||[];const {data:ss}=await sb.from('students').select('id,student_number,first_name,last_name').eq('organization_id',organizationId);const map=new Map((ss||[]).map(s=>[s.id,s]));setEnrolled(all.filter(e=>ids.includes(e.id)).map(e=>({...e,student:map.get(e.student_id)})));setAvailable(all.filter(e=>!ids.includes(e.id)&&e.level_id===c.level_id).map(e=>({...e,student:map.get(e.student_id)})))}
 const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const sb=createClient();const {data,error}=await sb.rpc('create_class_group',{p_organization_id:organizationId,p_name:form.name,p_code:form.code||null,p_capacity:form.capacity?Number(form.capacity):null,p_academic_year_id:year,p_level_id:form.level_id,p_program_id:form.program_id||null});if(error)throw error;setClasses(x=>[data,...x]);setOpen(false)}catch(err){setError(err instanceof Error?err.message:'Erreur')}finally{setSaving(false)}}
 const assign=async(enrollment_id:string)=>{if(!studentsOpen)return;const sb=createClient();const {data,error}=await sb.rpc('assign_student_to_class',{p_organization_id:organizationId,p_enrollment_id:enrollment_id,p_class_group_id:studentsOpen.id});if(error){setError(error.message);return}setAssignments(x=>[...x,data]);await loadStudents(studentsOpen)}
 const remove=async(id:string)=>{const sb=createClient();const {error}=await sb.rpc('remove_student_from_class',{p_assignment_id:id,p_organization_id:organizationId});if(error){setError(error.message);return}setAssignments(x=>x.filter(a=>a.id!==id));if(studentsOpen)await loadStudents(studentsOpen)}
 return <main className="students-page"><header className="students-top"><div><a className="back-link" href="/dashboard">← Tableau de bord</a><p className="eyebrow">SCOLARITÉ</p><h1>Classes & groupes</h1><p>Organisez les élèves par année scolaire, niveau et classe.</p></div><button className="student-primary" onClick={()=>{setSelected(null);setForm({name:'',code:'',capacity:'',level_id:'',program_id:''});setError('');setOpen(true)}}>+ Nouvelle classe</button></header><section className="student-toolbar"><select value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' · actuelle':''}</option>)}</select><strong>{filtered.length} classe{filtered.length!==1?'s':''}</strong></section><section className="module-grid">{filtered.map(c=><article className="module-card" key={c.id}><div className="module-icon">C</div><div><h3>{c.name}</h3><p>{lv(c.level_id)} {pr(c.program_id)?`· ${pr(c.program_id)}`:''} · {count(c.id)} élève{count(c.id)!==1?'s':''}{c.capacity?` / ${c.capacity}`:''}</p><button className="class-open" onClick={()=>loadStudents(c)}>Voir les élèves →</button></div></article>)}{filtered.length===0&&<div className="students-empty"><strong>Aucune classe</strong><span>Créez une classe pour cette année scolaire.</span></div>}</section>
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setOpen(false)}><section className="student-modal"><header><div><p className="eyebrow">CLASSE</p><h2>Nouvelle classe</h2></div><button className="modal-close" onClick={()=>setOpen(false)}>×</button></header><form onSubmit={create}><div className="form-grid"><label>Nom de la classe *<input required placeholder="Ex. 6ème A" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Code<input placeholder="6A" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Niveau *<select required value={form.level_id} onChange={e=>setForm({...form,level_id:e.target.value})}><option value="">Sélectionner</option>{levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Filière<select value={form.program_id} onChange={e=>setForm({...form,program_id:e.target.value})}><option value="">Aucune</option>{programs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Capacité<input type="number" min="1" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" className="student-secondary" onClick={()=>setOpen(false)}>Annuler</button><button disabled={saving} className="student-primary">{saving?'Création…':'Créer la classe'}</button></footer></form></section></div>}
 {studentsOpen&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setStudentsOpen(null)}><section className="student-modal wide-modal"><header><div><p className="eyebrow">LISTE DE CLASSE</p><h2>{studentsOpen.name}</h2><small>{enrolled.length} élève{enrolled.length!==1?'s':''}</small></div><button className="modal-close" onClick={()=>setStudentsOpen(null)}>×</button></header>{error&&<div className="form-error">{error}</div>}<div className="class-student-list">{enrolled.map(e=><div className="class-student-row" key={e.id}><div className="student-name"><div>{e.student?.first_name?.charAt(0)}{e.student?.last_name?.charAt(0)}</div><span><b>{e.student?.first_name} {e.student?.last_name}</b><small>{e.student?.student_number} · {e.enrollment_number}</small></span></div><a href={`/students?student=${e.student_id}`} className="student-secondary">Dossier</a><button className="remove-link" onClick={()=>remove(e.id)}>Retirer</button></div>)}{enrolled.length===0&&<p className="students-empty">Aucun élève dans cette classe.</p>}</div><div className="add-students"><h3>Ajouter un élève inscrit</h3>{available.map(e=><button key={e.id} onClick={()=>assign(e.id)}>{e.student?.first_name} {e.student?.last_name} — {e.student?.student_number}<span>+ Ajouter</span></button>)}{available.length===0&&<small>Tous les élèves admissibles sont déjà affectés.</small>}</div></section></div>}
 </main>
}
