use argon2::{password_hash::{rand_core::OsRng, PasswordHasher, SaltString}, Argon2};
use rusqlite::{params, Connection};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::State;
use uuid::Uuid;

const MIGRATION_001: &str = include_str!("../../../web/lib/local/migrations/001_initial_platform.sql");
const MIGRATION_002: &str = include_str!("../../../web/lib/local/migrations/002_local_admin_settings.sql");
const MIGRATION_003: &str = include_str!("../../../web/lib/local/migrations/003_academic_years_semesters.sql");
const MIGRATION_004: &str = include_str!("../../../web/lib/local/migrations/004_levels_departments.sql");
struct AppState { db: Mutex<Option<Connection>> }
#[derive(Debug,Serialize)] pub struct LocalRuntimeStatus { pub initialized:bool,pub database_path:String,pub root_path:String,pub migration_version:Option<i64> }
#[derive(Debug,Serialize)] pub struct LocalInstitution { pub id:String,pub name:String,pub slug:String,pub country_code:String,pub timezone:String,pub address:Option<String>,pub city:Option<String>,pub phone:Option<String>,pub email:Option<String>,pub website:Option<String>,pub logo_path:Option<String>,pub academic_year_label:Option<String>,pub created_at:String,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct LocalUser { pub id:String,pub username:String,pub first_name:String,pub last_name:String,pub phone:Option<String>,pub role:String,pub active:bool,pub institution_id:Option<String>,pub created_at:String,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct InstitutionSettings { pub institution_id:String,pub currency_code:String,pub locale:String,pub country_code:String,pub timezone:String,pub academic_year_label:Option<String>,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct AcademicYear { pub id:String,pub institution_id:String,pub label:String,pub start_date:String,pub end_date:String,pub status:String,pub is_current:bool,pub created_at:String,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct Semester { pub id:String,pub academic_year_id:String,pub name:String,pub code:String,pub start_date:String,pub end_date:String,pub sequence:i64,pub status:String,pub created_at:String,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct Level { pub id:String,pub institution_id:String,pub name:String,pub code:String,pub description:Option<String>,pub sequence:i64,pub status:String,pub created_at:String,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct Department { pub id:String,pub institution_id:String,pub name:String,pub code:String,pub description:Option<String>,pub status:String,pub created_at:String,pub updated_at:String }
#[derive(Debug,Serialize)] pub struct LocalError { pub code:String,pub message:String }
impl From<rusqlite::Error> for LocalError { fn from(e:rusqlite::Error)->Self{Self{code:"SQLITE_ERROR".into(),message:e.to_string()}} }
fn now()->String{SystemTime::now().duration_since(UNIX_EPOCH).map(|d|d.as_millis().to_string()).unwrap_or_else(|_|"0".into())}
fn root()->PathBuf{std::env::var("CONIK_DATA_ROOT").ok().filter(|v|!v.trim().is_empty()).map(PathBuf::from).unwrap_or_else(||PathBuf::from(r"C:\CONIK"))}
fn dirs(r:&Path)->Result<(),LocalError>{for p in [r.join("data"),r.join("documents/students"),r.join("documents/teachers"),r.join("documents/admissions"),r.join("documents/administrative"),r.join("generated/bulletins"),r.join("generated/transcripts"),r.join("generated/certificates"),r.join("generated/receipts"),r.join("generated/reports"),r.join("backups/automatic"),r.join("backups/manual"),r.join("logs"),r.join("config")]{fs::create_dir_all(&p).map_err(|e|LocalError{code:"FILESYSTEM_ERROR".into(),message:e.to_string()})?;}Ok(())}
fn open_database()->Result<(Connection,PathBuf),LocalError>{let r=root();dirs(&r)?;let p=r.join("data/conik.db");let c=Connection::open(&p)?;c.execute_batch("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;")?;c.execute_batch(MIGRATION_001)?;let v:i64=c.query_row("SELECT COALESCE(MAX(version),0) FROM schema_migrations",[],|r|r.get(0))?;if v<2{c.execute_batch(MIGRATION_002)?;}let v:i64=c.query_row("SELECT COALESCE(MAX(version),0) FROM schema_migrations",[],|r|r.get(0))?;if v<3{c.execute_batch(MIGRATION_003)?;}let v:i64=c.query_row("SELECT COALESCE(MAX(version),0) FROM schema_migrations",[],|r|r.get(0))?;if v<4{c.execute_batch(MIGRATION_004)?;}Ok((c,p))}
fn ensure(state:&State<AppState>)->Result<PathBuf,LocalError>{let mut g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;if g.is_none(){let(c,p)=open_database()?;*g=Some(c);return Ok(p)}Ok(root().join("data/conik.db"))}
fn lock(state:&State<AppState>)->Result<std::sync::MutexGuard<'_,Option<Connection>>,LocalError>{state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})}
#[tauri::command] pub fn initialize_local_runtime(state:State<AppState>)->Result<LocalRuntimeStatus,LocalError>{let p=ensure(&state)?;let g=lock(&state)?;let v=g.as_ref().and_then(|c|c.query_row("SELECT MAX(version) FROM schema_migrations",[],|r|r.get::<_,Option<i64>>(0)).ok().flatten());Ok(LocalRuntimeStatus{initialized:p.exists(),database_path:p.display().to_string(),root_path:root().display().to_string(),migration_version:v})}
#[tauri::command] pub fn get_local_runtime_status(state:State<AppState>)->Result<LocalRuntimeStatus,LocalError>{initialize_local_runtime(state)}
fn institution_row(r:&rusqlite::Row)->rusqlite::Result<LocalInstitution>{Ok(LocalInstitution{id:r.get(0)?,name:r.get(1)?,slug:r.get(2)?,country_code:r.get(3)?,timezone:r.get(4)?,address:r.get(5)?,city:r.get(6)?,phone:r.get(7)?,email:r.get(8)?,website:r.get(9)?,logo_path:r.get(10)?,academic_year_label:r.get(11)?,created_at:r.get(12)?,updated_at:r.get(13)?})}
fn user_row(r:&rusqlite::Row)->rusqlite::Result<LocalUser>{Ok(LocalUser{id:r.get(0)?,username:r.get(1)?,first_name:r.get(2)?,last_name:r.get(3)?,phone:r.get(4)?,role:r.get(5)?,active:r.get::<_,i64>(6)?==1,institution_id:r.get(7)?,created_at:r.get(8)?,updated_at:r.get(9)?})}
fn year_row(r:&rusqlite::Row)->rusqlite::Result<AcademicYear>{Ok(AcademicYear{id:r.get(0)?,institution_id:r.get(1)?,label:r.get(2)?,start_date:r.get(3)?,end_date:r.get(4)?,status:r.get(5)?,is_current:r.get::<_,i64>(6)?==1,created_at:r.get(7)?,updated_at:r.get(8)?})}
fn semester_row(r:&rusqlite::Row)->rusqlite::Result<Semester>{Ok(Semester{id:r.get(0)?,academic_year_id:r.get(1)?,name:r.get(2)?,code:r.get(3)?,start_date:r.get(4)?,end_date:r.get(5)?,sequence:r.get(6)?,status:r.get(7)?,created_at:r.get(8)?,updated_at:r.get(9)?})}
fn level_row(r:&rusqlite::Row)->rusqlite::Result<Level>{Ok(Level{id:r.get(0)?,institution_id:r.get(1)?,name:r.get(2)?,code:r.get(3)?,description:r.get(4)?,sequence:r.get(5)?,status:r.get(6)?,created_at:r.get(7)?,updated_at:r.get(8)?})}
fn department_row(r:&rusqlite::Row)->rusqlite::Result<Department>{Ok(Department{id:r.get(0)?,institution_id:r.get(1)?,name:r.get(2)?,code:r.get(3)?,description:r.get(4)?,status:r.get(5)?,created_at:r.get(6)?,updated_at:r.get(7)?})}
fn validate_dates(start:&str,end:&str)->Result<(),LocalError>{if start.trim().is_empty()||end.trim().is_empty()||start>=end{return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Start date must be before end date".into()})}Ok(())}
#[tauri::command] pub fn create_institution(state:State<AppState>,name:String,slug:String,country_code:Option<String>,timezone:Option<String>,address:Option<String>,city:Option<String>,phone:Option<String>,email:Option<String>,website:Option<String>,logo_path:Option<String>,academic_year_label:Option<String>)->Result<LocalInstitution,LocalError>{let n=name.trim();let s=slug.trim();if n.is_empty()||s.is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Institution name and slug are required".into()})}ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();let id=Uuid::new_v4().to_string();let t=now();let cc=country_code.unwrap_or("TG".into());let tz=timezone.unwrap_or("Africa/Lome".into());c.execute("INSERT INTO institution(id,name,slug,country_code,timezone,address,city,phone,email,website,logo_path,academic_year_label,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",params![id,n,s,cc,tz,address,city,phone,email,website,logo_path,academic_year_label,t,t])?;c.execute("INSERT INTO institution_settings(institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at) VALUES(?,'XOF','fr-FR',?,?,?,?)",params![id,cc,tz,academic_year_label,t])?;c.query_row("SELECT id,name,slug,country_code,timezone,address,city,phone,email,website,logo_path,academic_year_label,created_at,updated_at FROM institution WHERE id=?",params![id],institution_row).map_err(Into::into)}
#[tauri::command] pub fn get_institution(state:State<AppState>,id:String)->Result<Option<LocalInstitution>,LocalError>{ensure(&state)?;let g=lock(&state)?;match g.as_ref().unwrap().query_row("SELECT id,name,slug,country_code,timezone,address,city,phone,email,website,logo_path,academic_year_label,created_at,updated_at FROM institution WHERE id=?",params![id],institution_row){Ok(v)=>Ok(Some(v)),Err(rusqlite::Error::QueryReturnedNoRows)=>Ok(None),Err(e)=>Err(e.into())}}
#[tauri::command] pub fn bootstrap_local_admin(state:State<AppState>,institution_id:String,username:String,password:String,first_name:String,last_name:String,phone:Option<String>)->Result<LocalUser,LocalError>{let u=username.trim().to_lowercase();let f=first_name.trim();let l=last_name.trim();if institution_id.trim().is_empty()||u.is_empty()||password.len()<8||f.is_empty()||l.is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Institution, names, username and a password of at least 8 characters are required".into()})}ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM institution WHERE id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Institution not found".into()})}if c.query_row("SELECT 1 FROM local_users WHERE institution_id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_ok(){return Err(LocalError{code:"ADMIN_ALREADY_EXISTS".into(),message:"A local administrator already exists for this institution".into()})}if c.query_row("SELECT 1 FROM local_users WHERE username=?",params![u],|r|r.get::<_,i64>(0)).is_ok(){return Err(LocalError{code:"USERNAME_EXISTS".into(),message:"This username is already in use".into()})}let salt=SaltString::generate(&mut OsRng);let hash=Argon2::default().hash_password(password.as_bytes(),&salt).map_err(|e|LocalError{code:"PASSWORD_HASH_ERROR".into(),message:e.to_string()})?.to_string();let id=Uuid::new_v4().to_string();let t=now();c.execute("INSERT INTO local_users(id,username,password_hash,first_name,last_name,phone,role,active,institution_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'super_admin',1,?,?,?)",params![id,u,hash,f,l,phone,institution_id,t,t])?;c.query_row("SELECT id,username,first_name,last_name,phone,role,active,institution_id,created_at,updated_at FROM local_users WHERE id=?",params![id],user_row).map_err(Into::into)}
#[tauri::command] pub fn get_local_admin(state:State<AppState>,institution_id:String)->Result<Option<LocalUser>,LocalError>{ensure(&state)?;let g=lock(&state)?;match g.as_ref().unwrap().query_row("SELECT id,username,first_name,last_name,phone,role,active,institution_id,created_at,updated_at FROM local_users WHERE institution_id=? ORDER BY created_at LIMIT 1",params![institution_id],user_row){Ok(v)=>Ok(Some(v)),Err(rusqlite::Error::QueryReturnedNoRows)=>Ok(None),Err(e)=>Err(e.into())}}
fn settings_row(r:&rusqlite::Row)->rusqlite::Result<InstitutionSettings>{Ok(InstitutionSettings{institution_id:r.get(0)?,currency_code:r.get(1)?,locale:r.get(2)?,country_code:r.get(3)?,timezone:r.get(4)?,academic_year_label:r.get(5)?,updated_at:r.get(6)?})}
#[tauri::command] pub fn get_institution_settings(state:State<AppState>,institution_id:String)->Result<Option<InstitutionSettings>,LocalError>{ensure(&state)?;let g=lock(&state)?;match g.as_ref().unwrap().query_row("SELECT institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at FROM institution_settings WHERE institution_id=?",params![institution_id],settings_row){Ok(v)=>Ok(Some(v)),Err(rusqlite::Error::QueryReturnedNoRows)=>Ok(None),Err(e)=>Err(e.into())}}
#[tauri::command] pub fn update_institution_settings(state:State<AppState>,institution_id:String,currency_code:String,locale:String,country_code:String,timezone:String,academic_year_label:Option<String>)->Result<InstitutionSettings,LocalError>{if currency_code.trim().is_empty()||locale.trim().is_empty()||country_code.trim().is_empty()||timezone.trim().is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Currency, locale, country and timezone are required".into()})}ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();let t=now();c.execute("INSERT INTO institution_settings(institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(institution_id) DO UPDATE SET currency_code=excluded.currency_code,locale=excluded.locale,country_code=excluded.country_code,timezone=excluded.timezone,academic_year_label=excluded.academic_year_label,updated_at=excluded.updated_at",params![institution_id,currency_code,locale,country_code,timezone,academic_year_label,t])?;c.query_row("SELECT institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at FROM institution_settings WHERE institution_id=?",params![institution_id],settings_row).map_err(Into::into)}
#[tauri::command] pub fn create_academic_year(state:State<AppState>,institution_id:String,label:String,start_date:String,end_date:String,set_current:bool)->Result<AcademicYear,LocalError>{if label.trim().is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Academic year label is required".into()})}validate_dates(&start_date,&end_date)?;ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM institution WHERE id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Institution not found".into()})}if set_current{c.execute("UPDATE academic_years_local SET is_current=0,status=CASE WHEN status='active' THEN 'planned' ELSE status END,updated_at=? WHERE institution_id=?",params![now(),institution_id])?;}let id=Uuid::new_v4().to_string();let t=now();c.execute("INSERT INTO academic_years_local(id,institution_id,label,start_date,end_date,status,is_current,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",params![id,institution_id,label.trim(),start_date,end_date,if set_current{"active"}else{"planned"},if set_current{1}else{0},t,t])?;c.query_row("SELECT id,institution_id,label,start_date,end_date,status,is_current,created_at,updated_at FROM academic_years_local WHERE id=?",params![id],year_row).map_err(Into::into)}
#[tauri::command] pub fn list_academic_years(state:State<AppState>,institution_id:String)->Result<Vec<AcademicYear>,LocalError>{ensure(&state)?;let g=lock(&state)?;let mut st=g.as_ref().unwrap().prepare("SELECT id,institution_id,label,start_date,end_date,status,is_current,created_at,updated_at FROM academic_years_local WHERE institution_id=? ORDER BY start_date DESC")?;let rows=st.query_map(params![institution_id],year_row)?;Ok(rows.collect::<Result<Vec<_>,_>>()?)}
#[tauri::command] pub fn set_current_academic_year(state:State<AppState>,institution_id:String,academic_year_id:String)->Result<AcademicYear,LocalError>{ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM academic_years_local WHERE id=? AND institution_id=?",params![academic_year_id,institution_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Academic year not found".into()})}let t=now();c.execute("UPDATE academic_years_local SET is_current=0,updated_at=? WHERE institution_id=?",params![t,institution_id])?;c.execute("UPDATE academic_years_local SET is_current=1,status='active',updated_at=? WHERE id=?",params![t,academic_year_id])?;c.query_row("SELECT id,institution_id,label,start_date,end_date,status,is_current,created_at,updated_at FROM academic_years_local WHERE id=?",params![academic_year_id],year_row).map_err(Into::into)}
#[tauri::command] pub fn create_semester(state:State<AppState>,academic_year_id:String,name:String,code:String,start_date:String,end_date:String,sequence:i64)->Result<Semester,LocalError>{if name.trim().is_empty()||code.trim().is_empty()||sequence<1{return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Semester name, code and a positive sequence are required".into()})}validate_dates(&start_date,&end_date)?;ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM academic_years_local WHERE id=?",params![academic_year_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Academic year not found".into()})}let id=Uuid::new_v4().to_string();let t=now();c.execute("INSERT INTO semesters_local(id,academic_year_id,name,code,start_date,end_date,sequence,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'planned',?,?)",params![id,academic_year_id,name.trim(),code.trim(),start_date,end_date,sequence,t,t])?;c.query_row("SELECT id,academic_year_id,name,code,start_date,end_date,sequence,status,created_at,updated_at FROM semesters_local WHERE id=?",params![id],semester_row).map_err(Into::into)}
#[tauri::command] pub fn list_semesters(state:State<AppState>,academic_year_id:String)->Result<Vec<Semester>,LocalError>{ensure(&state)?;let g=lock(&state)?;let mut st=g.as_ref().unwrap().prepare("SELECT id,academic_year_id,name,code,start_date,end_date,sequence,status,created_at,updated_at FROM semesters_local WHERE academic_year_id=? ORDER BY sequence")?;let rows=st.query_map(params![academic_year_id],semester_row)?;Ok(rows.collect::<Result<Vec<_>,_>>()?)}
#[tauri::command] pub fn create_level(state:State<AppState>,institution_id:String,name:String,code:String,description:Option<String>,sequence:i64)->Result<Level,LocalError>{let n=name.trim();let cde=code.trim();if institution_id.trim().is_empty()||n.is_empty()||cde.is_empty()||sequence<1{return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Institution, level name, code and a positive sequence are required".into()})}ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM institution WHERE id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Institution not found".into()})}let id=Uuid::new_v4().to_string();let t=now();c.execute("INSERT INTO levels_local(id,institution_id,name,code,description,sequence,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'active',?,?)",params![id,institution_id,n,cde,description,sequence,t,t])?;c.query_row("SELECT id,institution_id,name,code,description,sequence,status,created_at,updated_at FROM levels_local WHERE id=?",params![id],level_row).map_err(Into::into)}
#[tauri::command] pub fn list_levels(state:State<AppState>,institution_id:String)->Result<Vec<Level>,LocalError>{ensure(&state)?;let g=lock(&state)?;let mut st=g.as_ref().unwrap().prepare("SELECT id,institution_id,name,code,description,sequence,status,created_at,updated_at FROM levels_local WHERE institution_id=? ORDER BY sequence,name")?;let rows=st.query_map(params![institution_id],level_row)?;Ok(rows.collect::<Result<Vec<_>,_>>()?)}
#[tauri::command] pub fn create_department(state:State<AppState>,institution_id:String,name:String,code:String,description:Option<String>)->Result<Department,LocalError>{let n=name.trim();let cde=code.trim();if institution_id.trim().is_empty()||n.is_empty()||cde.is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Institution, department name and code are required".into()})}ensure(&state)?;let g=lock(&state)?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM institution WHERE id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Institution not found".into()})}let id=Uuid::new_v4().to_string();let t=now();c.execute("INSERT INTO departments_local(id,institution_id,name,code,description,status,created_at,updated_at) VALUES(?,?,?,?,?,'active',?,?)",params![id,institution_id,n,cde,description,t,t])?;c.query_row("SELECT id,institution_id,name,code,description,status,created_at,updated_at FROM departments_local WHERE id=?",params![id],department_row).map_err(Into::into)}
#[tauri::command] pub fn list_departments(state:State<AppState>,institution_id:String)->Result<Vec<Department>,LocalError>{ensure(&state)?;let g=lock(&state)?;let mut st=g.as_ref().unwrap().prepare("SELECT id,institution_id,name,code,description,status,created_at,updated_at FROM departments_local WHERE institution_id=? ORDER BY name")?;let rows=st.query_map(params![institution_id],department_row)?;Ok(rows.collect::<Result<Vec<_>,_>>()?)}
pub fn run(){tauri::Builder::default().manage(AppState{db:Mutex::new(None)}).invoke_handler(tauri::generate_handler![initialize_local_runtime,get_local_runtime_status,create_institution,get_institution,bootstrap_local_admin,get_local_admin,get_institution_settings,update_institution_settings,create_academic_year,list_academic_years,set_current_academic_year,create_semester,list_semesters,create_level,list_levels,create_department,list_departments]).run(tauri::generate_context!()).expect("error while running CONIK desktop application");}
