use argon2::{password_hash::{rand_core::OsRng, PasswordHasher, SaltString}, Argon2};
use rusqlite::{params, Connection};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::State;
use uuid::Uuid;

const MIGRATION_001: &str = include_str!("../../../web/lib/local/migrations/001_initial_platform.sql");
const MIGRATION_002: &str = include_str!("../../../web/lib/local/migrations/002_local_admin_settings.sql");
struct AppState { db: Mutex<Option<Connection>> }
#[derive(Debug, Serialize)] pub struct LocalRuntimeStatus { pub initialized: bool, pub database_path: String, pub root_path: String, pub migration_version: Option<i64> }
#[derive(Debug, Serialize)] pub struct LocalInstitution { pub id:String,pub name:String,pub slug:String,pub country_code:String,pub timezone:String,pub address:Option<String>,pub city:Option<String>,pub phone:Option<String>,pub email:Option<String>,pub website:Option<String>,pub logo_path:Option<String>,pub academic_year_label:Option<String>,pub created_at:String,pub updated_at:String }
#[derive(Debug, Serialize)] pub struct LocalUser { pub id:String,pub username:String,pub first_name:String,pub last_name:String,pub phone:Option<String>,pub role:String,pub active:bool,pub institution_id:Option<String>,pub created_at:String,pub updated_at:String }
#[derive(Debug, Serialize)] pub struct InstitutionSettings { pub institution_id:String,pub currency_code:String,pub locale:String,pub country_code:String,pub timezone:String,pub academic_year_label:Option<String>,pub updated_at:String }
#[derive(Debug, Serialize)] pub struct LocalError { pub code:String,pub message:String }
impl From<rusqlite::Error> for LocalError { fn from(e:rusqlite::Error)->Self{Self{code:"SQLITE_ERROR".into(),message:e.to_string()}} }
fn now()->String{SystemTime::now().duration_since(UNIX_EPOCH).map(|d|d.as_millis().to_string()).unwrap_or_else(|_|"0".into())}
fn conik_root()->PathBuf{std::env::var("CONIK_DATA_ROOT").ok().filter(|v|!v.trim().is_empty()).map(PathBuf::from).unwrap_or_else(||PathBuf::from(r"C:\CONIK"))}
fn create_directories(root:&Path)->Result<(),LocalError>{for p in [root.join("data"),root.join("documents/students"),root.join("documents/teachers"),root.join("documents/admissions"),root.join("documents/administrative"),root.join("generated/bulletins"),root.join("generated/transcripts"),root.join("generated/certificates"),root.join("generated/receipts"),root.join("generated/reports"),root.join("backups/automatic"),root.join("backups/manual"),root.join("logs"),root.join("config")]{fs::create_dir_all(&p).map_err(|e|LocalError{code:"FILESYSTEM_ERROR".into(),message:e.to_string()})?;}Ok(())}
fn open_database()->Result<(Connection,PathBuf),LocalError>{let r=conik_root();create_directories(&r)?;let p=r.join("data/conik.db");let c=Connection::open(&p)?;c.execute_batch("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;")?;c.execute_batch(MIGRATION_001)?;let v:i64=c.query_row("SELECT COALESCE(MAX(version),0) FROM schema_migrations",[],|row|row.get(0))?;if v<2{c.execute_batch(MIGRATION_002)?;}Ok((c,p))}
fn ensure_connection(state:&State<AppState>)->Result<PathBuf,LocalError>{let mut g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;if g.is_none(){let(c,p)=open_database()?;*g=Some(c);return Ok(p)}Ok(conik_root().join("data/conik.db"))}
fn status(state:&State<AppState>)->Result<LocalRuntimeStatus,LocalError>{let p=ensure_connection(state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;let v=g.as_ref().and_then(|c|c.query_row("SELECT MAX(version) FROM schema_migrations",[],|r|r.get::<_,Option<i64>>(0)).ok().flatten());Ok(LocalRuntimeStatus{initialized:p.exists(),database_path:p.display().to_string(),root_path:conik_root().display().to_string(),migration_version:v})}
#[tauri::command] pub fn initialize_local_runtime(state:State<AppState>)->Result<LocalRuntimeStatus,LocalError>{status(&state)}
#[tauri::command] pub fn get_local_runtime_status(state:State<AppState>)->Result<LocalRuntimeStatus,LocalError>{status(&state)}
fn institution_row(r:&rusqlite::Row)->rusqlite::Result<LocalInstitution>{Ok(LocalInstitution{id:r.get(0)?,name:r.get(1)?,slug:r.get(2)?,country_code:r.get(3)?,timezone:r.get(4)?,address:r.get(5)?,city:r.get(6)?,phone:r.get(7)?,email:r.get(8)?,website:r.get(9)?,logo_path:r.get(10)?,academic_year_label:r.get(11)?,created_at:r.get(12)?,updated_at:r.get(13)?})}
#[tauri::command] pub fn create_institution(state:State<AppState>,name:String,slug:String,country_code:Option<String>,timezone:Option<String>,address:Option<String>,city:Option<String>,phone:Option<String>,email:Option<String>,website:Option<String>,logo_path:Option<String>,academic_year_label:Option<String>)->Result<LocalInstitution,LocalError>{let n=name.trim();let s=slug.trim();if n.is_empty()||s.is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Institution name and slug are required".into()})}ensure_connection(&state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;let c=g.as_ref().unwrap();let id=Uuid::new_v4().to_string();let t=now();let cc=country_code.unwrap_or("TG".into());let tz=timezone.unwrap_or("Africa/Lome".into());c.execute("INSERT INTO institution(id,name,slug,country_code,timezone,address,city,phone,email,website,logo_path,academic_year_label,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",params![id,n,s,cc,tz,address,city,phone,email,website,logo_path,academic_year_label,t,t])?;c.execute("INSERT INTO institution_settings(institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at) VALUES(?,'XOF','fr-FR',?,?,?,?)",params![id,cc,tz,academic_year_label,t])?;c.query_row("SELECT id,name,slug,country_code,timezone,address,city,phone,email,website,logo_path,academic_year_label,created_at,updated_at FROM institution WHERE id=?",params![id],institution_row).map_err(Into::into)}
#[tauri::command] pub fn get_institution(state:State<AppState>,id:String)->Result<Option<LocalInstitution>,LocalError>{ensure_connection(&state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;match g.as_ref().unwrap().query_row("SELECT id,name,slug,country_code,timezone,address,city,phone,email,website,logo_path,academic_year_label,created_at,updated_at FROM institution WHERE id=?",params![id],institution_row){Ok(v)=>Ok(Some(v)),Err(rusqlite::Error::QueryReturnedNoRows)=>Ok(None),Err(e)=>Err(e.into())}}
fn user_row(r:&rusqlite::Row)->rusqlite::Result<LocalUser>{Ok(LocalUser{id:r.get(0)?,username:r.get(1)?,first_name:r.get(2)?,last_name:r.get(3)?,phone:r.get(4)?,role:r.get(5)?,active:r.get::<_,i64>(6)?==1,institution_id:r.get(7)?,created_at:r.get(8)?,updated_at:r.get(9)?})}
#[tauri::command] pub fn bootstrap_local_admin(state:State<AppState>,institution_id:String,username:String,password:String,first_name:String,last_name:String,phone:Option<String>)->Result<LocalUser,LocalError>{let u=username.trim().to_lowercase();let f=first_name.trim();let l=last_name.trim();if institution_id.trim().is_empty()||u.is_empty()||password.len()<8||f.is_empty()||l.is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Institution, names, username and a password of at least 8 characters are required".into()})}ensure_connection(&state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;let c=g.as_ref().unwrap();if c.query_row("SELECT 1 FROM institution WHERE id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_err(){return Err(LocalError{code:"NOT_FOUND".into(),message:"Institution not found".into()})}if c.query_row("SELECT 1 FROM local_users WHERE institution_id=?",params![institution_id],|r|r.get::<_,i64>(0)).is_ok(){return Err(LocalError{code:"ADMIN_ALREADY_EXISTS".into(),message:"A local administrator already exists for this institution".into()})}if c.query_row("SELECT 1 FROM local_users WHERE username=?",params![u],|r|r.get::<_,i64>(0)).is_ok(){return Err(LocalError{code:"USERNAME_EXISTS".into(),message:"This username is already in use".into()})}let salt=SaltString::generate(&mut OsRng);let hash=Argon2::default().hash_password(password.as_bytes(),&salt).map_err(|e|LocalError{code:"PASSWORD_HASH_ERROR".into(),message:e.to_string()})?.to_string();let id=Uuid::new_v4().to_string();let t=now();c.execute("INSERT INTO local_users(id,username,password_hash,first_name,last_name,phone,role,active,institution_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'super_admin',1,?,?,?)",params![id,u,hash,f,l,phone,institution_id,t,t])?;c.query_row("SELECT id,username,first_name,last_name,phone,role,active,institution_id,created_at,updated_at FROM local_users WHERE id=?",params![id],user_row).map_err(Into::into)}
#[tauri::command] pub fn get_local_admin(state:State<AppState>,institution_id:String)->Result<Option<LocalUser>,LocalError>{ensure_connection(&state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;match g.as_ref().unwrap().query_row("SELECT id,username,first_name,last_name,phone,role,active,institution_id,created_at,updated_at FROM local_users WHERE institution_id=? ORDER BY created_at LIMIT 1",params![institution_id],user_row){Ok(v)=>Ok(Some(v)),Err(rusqlite::Error::QueryReturnedNoRows)=>Ok(None),Err(e)=>Err(e.into())}}
fn settings_row(r:&rusqlite::Row)->rusqlite::Result<InstitutionSettings>{Ok(InstitutionSettings{institution_id:r.get(0)?,currency_code:r.get(1)?,locale:r.get(2)?,country_code:r.get(3)?,timezone:r.get(4)?,academic_year_label:r.get(5)?,updated_at:r.get(6)?})}
#[tauri::command] pub fn get_institution_settings(state:State<AppState>,institution_id:String)->Result<Option<InstitutionSettings>,LocalError>{ensure_connection(&state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;match g.as_ref().unwrap().query_row("SELECT institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at FROM institution_settings WHERE institution_id=?",params![institution_id],settings_row){Ok(v)=>Ok(Some(v)),Err(rusqlite::Error::QueryReturnedNoRows)=>Ok(None),Err(e)=>Err(e.into())}}
#[tauri::command] pub fn update_institution_settings(state:State<AppState>,institution_id:String,currency_code:String,locale:String,country_code:String,timezone:String,academic_year_label:Option<String>)->Result<InstitutionSettings,LocalError>{if currency_code.trim().is_empty()||locale.trim().is_empty()||country_code.trim().is_empty()||timezone.trim().is_empty(){return Err(LocalError{code:"VALIDATION_ERROR".into(),message:"Currency, locale, country and timezone are required".into()})}ensure_connection(&state)?;let g=state.db.lock().map_err(|_|LocalError{code:"DB_LOCK_ERROR".into(),message:"Unable to acquire local database lock".into()})?;let c=g.as_ref().unwrap();let t=now();c.execute("INSERT INTO institution_settings(institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(institution_id) DO UPDATE SET currency_code=excluded.currency_code,locale=excluded.locale,country_code=excluded.country_code,timezone=excluded.timezone,academic_year_label=excluded.academic_year_label,updated_at=excluded.updated_at",params![institution_id,currency_code,locale,country_code,timezone,academic_year_label,t])?;c.query_row("SELECT institution_id,currency_code,locale,country_code,timezone,academic_year_label,updated_at FROM institution_settings WHERE institution_id=?",params![institution_id],settings_row).map_err(Into::into)}
pub fn run(){tauri::Builder::default().manage(AppState{db:Mutex::new(None)}).invoke_handler(tauri::generate_handler![initialize_local_runtime,get_local_runtime_status,create_institution,get_institution,bootstrap_local_admin,get_local_admin,get_institution_settings,update_institution_settings]).run(tauri::generate_context!()).expect("error while running CONIK desktop application");}
