'use client'

import { useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Student = { id:string; student_number:string; first_name:string; last_name:string; sex:string|null; date_of_birth:string|null; phone:string|null; email:string|null; address:string|null; parent_name:string|null; parent_phone:string|null; program_id:string|null; level_id:string|null; academic_year_id:string|null; status:string; created_at:string }
type Option = { id:string; name:string; code?:string|null }
type Form = { first_name:string; last_name:string; sex:string; date_of_birth:string; phone:string; email:string; address:string; parent_name:string; parent_phone:string; program_id:string; level_id:string; academic_year_id:string }
const empty:Form={first_name:'',last_name:'',sex:'',date_of_birth:'',phone:'',email:'',address:'',parent_name:'',parent_phone:'',program_id:'',level_id:'',academic_year_id:''}

export default function StudentManager({organizationId,initialStudents,programs,levels,years}:{organizationId:string;initialStudents:Student[];programs:Option[];levels:Option[];years:Option[]}){
 const [students,setStudents]=useState(initialStudents); const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<Student|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState<Form>({...empty,academic_year_id:years[0]?.id||''})
 const filtered=useMemo(()=>students.filter(s=>{const q=search.toLowerCase().trim(); const matches=!q||`${s.first_name} ${s.last_name} ${s.student_number} ${s.email||''} ${s.phone||''}`.toLowerCase().includes(q); return matches&&(status==='all'||s.status===status)}),[students,search,status])
 const set=(k:keyof Form,v:string)=>setForm(f=>({...f,[k]:v}))
 const openStudent=(s:Student)=>{setSelected(s);setForm({first_name:s.first_name,last_name:s.last_name,sex:s.sex||'',date_of_birth:s.date_of_birth||'',phone:s.phone||'',email:s.email||'',address:s.address||'',parent_name:s.parent_name||'',parent_phone:s.parent_phone||'',program_id:s.program_id||'',level_id:s.level_id||'',academic_year_id:s.academic_year_id||''});setError('')}
 const close=()=>{setOpen(false);setSelected(null);setError('')}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{const supabase=createClient();if(!selected){const {data,error}=await supabase.rpc('create_student',{p_organization_id:organizationId,p_first_name:form.first_name,p_last_name:form.last_name,p_sex:form.sex||null,p_date_of_birth:form.date_of_birth||null,p_phone:form.phone||null,p_email:form.email||null,p_address:form.address||null,p_parent_name:form.parent_name||null,p_parent_phone:form.parent_phone||null,p_program_id:form.program_id||null,p_level_id:form.level_id||null,p_academic_year_id:form.academic_year_id||null});if(error)throw error;setStudents(s=>[data,...s])}else{const {data,error}=await supabase.rpc('update_student',{p_student_id:selected.id,p_organization_id:organizationId,p_first_name:form.first_name,p_last_name:form.last_name,p_sex:form.sex||null,p_date_of_birth:form.date_of_birth||null,p_phone:form.phone||null,p_email:form.email||null,p_address:form.address||null,p_parent_name:form.parent_name||null,p_parent_phone:form.parent_phone||null,p_program_id:form.program_id||null,p_level_id:form.level_id||null,p_academic_year_id:form.academic_year_id||null});if(error)throw error;setStudents(s=>s.map(x=>x.id===selected.id?data:x))}close()}catch(err){setError(err instanceof Error?err.message:'Une erreur est survenue.')}finally{setSaving(false)}}
 const program=(id:string|null)=>programs.find(x=>x.id===id); const level=(id:string|null)=>levels.find(x=>x.id===id)
 const statusLabel=(v:string)=>v==='active'?'Actif':v==='graduated'?'Diplômé':'Inactif'
 return <main className="students-page"><header className="students-top"><div><a className="back-link" href="/dashboard">← Tableau de bord</a><p className="eyebrow">SCOLARITÉ</p><h1>Étudiants</h1><p>Gérez les dossiers étudiants de votre établissement.</p></div><button className="student-primary" onClick={()=>{setSelected(null);setForm({...empty,academic_year_id:years[0]?.id||''});setError('');setOpen(true)}}>+ Nouvel étudiant</button></header>
 <section className="student-toolbar"><div className="student-search"><span>⌕</span><input placeholder="Rechercher par nom, matricule, téléphone…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous les statuts</option><option value="active">Actifs</option><option value="inactive">Inactifs</option><option value="graduated">Diplômés</option></select><strong>{filtered.length} étudiant{filtered.length!==1?'s':''}</strong></section>
 <section className="students-table-wrap"><table><thead><tr><th>Étudiant</th><th>Matricule</th><th>Formation</th><th>Niveau</th><th>Contact</th><th>Statut</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} onClick={()=>openStudent(s)}><td><div className="student-name"><div>{s.first_name.charAt(0)}{s.last_name.charAt(0)}</div><span><b>{s.first_name} {s.last_name}</b><small>{s.email||'Aucun email'}</small></span></div></td><td><code>{s.student_number}</code></td><td>{program(s.program_id)?.name||'—'}</td><td>{level(s.level_id)?.name||'—'}</td><td>{s.phone||'—'}</td><td><span className={`status status-${s.status}`}>{statusLabel(s.status)}</span></td></tr>)}{filtered.length===0&&<tr><td colSpan={6}><div className="students-empty"><strong>Aucun étudiant trouvé</strong><span>Modifiez votre recherche ou créez un nouveau dossier.</span></div></td></tr>}</tbody></table></section>
 {(open||selected)&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&close()}><section className="student-modal"><header><div><p className="eyebrow">{selected?'DOSSIER ÉTUDIANT':'NOUVEAU DOSSIER'}</p><h2>{selected?`${selected.first_name} ${selected.last_name}`:'Ajouter un étudiant'}</h2>{selected&&<small className="modal-number">Matricule : {selected.student_number}</small>}</div><button type="button" className="modal-close" onClick={close}>×</button></header><form onSubmit={save}><div className="form-grid"><label>Prénom *<input required value={form.first_name} onChange={e=>set('first_name',e.target.value)}/></label><label>Nom *<input required value={form.last_name} onChange={e=>set('last_name',e.target.value)}/></label><label>Sexe<select value={form.sex} onChange={e=>set('sex',e.target.value)}><option value="">Sélectionner</option><option value="M">Masculin</option><option value="F">Féminin</option></select></label><label>Date de naissance<input type="date" value={form.date_of_birth} onChange={e=>set('date_of_birth',e.target.value)}/></label><label>Téléphone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Filière<select value={form.program_id} onChange={e=>set('program_id',e.target.value)}><option value="">Sélectionner</option>{programs.map(x=><option key={x.id} value={x.id}>{x.name}{x.code?` (${x.code})`:''}</option>)}</select></label><label>Niveau<select value={form.level_id} onChange={e=>set('level_id',e.target.value)}><option value="">Sélectionner</option>{levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Année académique<select value={form.academic_year_id} onChange={e=>set('academic_year_id',e.target.value)}><option value="">Aucune</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Adresse<input value={form.address} onChange={e=>set('address',e.target.value)}/></label><label>Parent / tuteur<input value={form.parent_name} onChange={e=>set('parent_name',e.target.value)}/></label><label>Téléphone parent<input value={form.parent_phone} onChange={e=>set('parent_phone',e.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" className="student-secondary" onClick={close}>Annuler</button><button disabled={saving} className="student-primary" type="submit">{saving?'Enregistrement…':selected?'Enregistrer les modifications':'Créer le dossier'}</button></footer></form></section></div>}
 </main>
}
