'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type GradeRow={subject:string;interrogations:string;devoirs:string;controles:string;examen:string;average:number;coefficient:number}
type Student={id:string;name:string;number:string;average:number;rank:number;rows:GradeRow[]}
type Block={id:string;type:string;x:number;y:number;width:number;height:number;fontSize:number;text:string;opacity:number}
type Template={name:string;pageSize:string;blocks:Block[]}
type ClassItem={id:string;name:string;code:string;academic_year_id:string}
type YearItem={id:string;name:string;is_current:boolean}
type PeriodItem={id:string;name:string;academic_year_id:string;semester_number:number}

const fallbackTemplate:Template={name:'Bulletin collège - Trimestre',pageSize:'A4',blocks:[
 {id:'b1',type:'school_logo',x:35,y:28,width:90,height:70,fontSize:14,text:'{{school_logo}}',opacity:1},
 {id:'b2',type:'heading',x:140,y:35,width:500,height:45,fontSize:22,text:'{{school_name}}',opacity:1},
 {id:'b3',type:'heading',x:170,y:90,width:440,height:42,fontSize:22,text:'BULLETIN SCOLAIRE',opacity:1},
 {id:'b4',type:'student_info',x:35,y:150,width:700,height:62,fontSize:13,text:'Élève : {{student_name}} • Matricule : {{student_number}} • Classe : {{class_name}} • Année : {{academic_year}}',opacity:1},
 {id:'b5',type:'grades_table',x:35,y:235,width:700,height:285,fontSize:11,text:'MATIÈRE | INTERROGATIONS | DEVOIRS | CONTRÔLES | EXAMEN | MOYENNE | COEF.',opacity:1},
 {id:'b6',type:'average',x:440,y:550,width:295,height:42,fontSize:16,text:'Moyenne générale : {{general_average}} / 20',opacity:1},
 {id:'b7',type:'rank',x:440,y:600,width:295,height:35,fontSize:14,text:'Rang : {{rank}}',opacity:1},
 {id:'b8',type:'watermark',x:180,y:335,width:420,height:90,fontSize:34,text:'{{school_name}}',opacity:.09},
 {id:'b9',type:'signature',x:35,y:660,width:700,height:48,fontSize:12,text:'Signature du professeur principal                 Direction / Cachet',opacity:1},
]}

function score(g:number,max:number){return max>0?Math.round((g/max)*20*100)/100:null}
function assessmentKind(v:string){const x=v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(x.includes('interro'))return'interrogation';if(x.includes('devoir')||x==='classe'||x==='classwork')return'devoir';if(x.includes('control'))return'controle';if(x.includes('exam')||x.includes('partiel'))return'examen';return'autre'}

export default function BulletinsPage(){
 const sb=useMemo(()=>createClient(),[])
 const [orgId,setOrgId]=useState(''),[classes,setClasses]=useState<ClassItem[]>([]),[years,setYears]=useState<YearItem[]>([]),[periods,setPeriods]=useState<PeriodItem[]>([])
 const [classId,setClassId]=useState(''),[yearId,setYearId]=useState(''),[periodId,setPeriodId]=useState('')
 const [students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[status,setStatus]=useState(''),[selected,setSelected]=useState<Student|null>(null),[template,setTemplate]=useState<Template>(fallbackTemplate)
 const className=classes.find(c=>c.id===classId)?.name||'Classe'; const period=periods.find(p=>p.id===periodId)?.name||'Période'; const yearName=years.find(y=>y.id===yearId)?.name||'Année scolaire'

 useEffect(()=>{try{const raw=localStorage.getItem('conik_bulletin_template');if(raw){const parsed=JSON.parse(raw);if(parsed?.blocks?.length)setTemplate(parsed)}}catch{setStatus('Le modèle local n’a pas pu être chargé. Le modèle par défaut est utilisé.')}
  ;(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){setStatus('Session utilisateur introuvable.');setLoading(false);return}const {data:m}=await sb.from('organization_members').select('organization_id').eq('user_id',user.id).maybeSingle();if(!m?.organization_id){setStatus('Aucun établissement associé à votre compte.');setLoading(false);return}setOrgId(m.organization_id);const [{data:c},{data:y},{data:p}]=await Promise.all([sb.from('class_groups').select('id,name,code,academic_year_id').eq('organization_id',m.organization_id).eq('is_active',true).order('name'),sb.from('academic_years').select('id,name,is_current').eq('organization_id',m.organization_id).order('is_current',{ascending:false}).order('starts_on',{ascending:false}),sb.from('academic_semesters').select('id,name,semester_number,academic_year_id').eq('organization_id',m.organization_id).order('semester_number')]);setClasses(c??[]);setYears(y??[]);setPeriods(p??[]);const cy=(y??[]).find(v=>v.is_current)??(y??[])[0];setYearId(cy?.id||'');const cc=(c??[]).find(v=>v.academic_year_id===cy?.id)??(c??[])[0];setClassId(cc?.id||'');const pp=(p??[]).find(v=>v.academic_year_id===cy?.id)??(p??[])[0];setPeriodId(pp?.id||'');setLoading(false)})()
 },[sb])

 useEffect(()=>{if(!orgId||!classId||!yearId||!periodId)return;setLoading(true);setStatus('Chargement des données réelles du bulletin…');(async()=>{const [{data:assignments,error:ae},{data:assessments,error:asse}]=await Promise.all([sb.from('student_class_assignments').select('enrollment_id,student_enrollments!inner(student_id,academic_year_id,status,students!inner(id,student_number,first_name,last_name,status))').eq('organization_id',orgId).eq('class_group_id',classId).eq('status','active'),sb.from('assessments').select('id,subject_id,title,assessment_type,max_value,coefficient').eq('organization_id',orgId).eq('class_group_id',classId).eq('academic_year_id',yearId).eq('semester_id',periodId)]);if(ae||asse){setStatus(`Impossible de charger les données : ${ae?.message||asse?.message}`);setLoading(false);return}const ids=(assignments??[]).map((a:any)=>a.student_enrollments.student_id);if(!ids.length){setStudents([]);setStatus('Aucun élève actif dans cette classe pour cette année.');setLoading(false);return}const assessmentIds=(assessments??[]).map(a=>a.id);const [{data:grades},{data:subjects}]=await Promise.all([assessmentIds.length?sb.from('grades').select('assessment_id,student_id,value').eq('organization_id',orgId).in('assessment_id',assessmentIds).in('student_id',ids):Promise.resolve({data:[] as any[]}),sb.from('subjects').select('id,name,coefficient').eq('organization_id',orgId)]);const subjectMap=new Map((subjects??[]).map(s=>[s.id,s]));const gradeMap=new Map((grades??[]).map(g=>[`${g.student_id}:${g.assessment_id}`,g.value]));const built:Student[]=(assignments??[]).map((a:any)=>{const st=a.student_enrollments.students;const bySub=new Map<string,GradeRow>();for(const ass of assessments??[]){const sub=subjectMap.get(ass.subject_id);if(!sub)continue;const key=sub.id;const row=bySub.get(key)??{subject:sub.name,interrogations:'—',devoirs:'—',controles:'—',examen:'—',average:0,coefficient:Number(sub.coefficient||1)};const raw=gradeMap.get(`${st.id}:${ass.id}`);const v=raw==null?null:score(Number(raw),Number(ass.max_value));if(v!=null){const k=assessmentKind(ass.assessment_type);if(k==='interrogation')row.interrogations=v.toFixed(2);else if(k==='devoir')row.devoirs=v.toFixed(2);else if(k==='controle')row.controles=v.toFixed(2);else if(k==='examen')row.examen=v.toFixed(2);}
 bySub.set(key,row)}const rows=[...bySub.values()];for(const row of rows){const vals=[row.interrogations,row.devoirs,row.controles,row.examen].filter(v=>v!=='—').map(Number);row.average=vals.length?Number((vals.reduce((x,n)=>x+n,0)/vals.length).toFixed(2)):0}const totalCoef=rows.reduce((x,r)=>x+(r.average>0?r.coefficient:0),0);const avg=totalCoef?Number((rows.reduce((x,r)=>x+r.average*r.coefficient,0)/totalCoef).toFixed(2)):0;return{id:st.id,name:`${st.first_name} ${st.last_name}`.trim(),number:st.student_number||'—',average:avg,rank:0,rows}}).sort((a,b)=>b.average-a.average);built.forEach((s,i)=>{s.rank=i+1});setStudents(built);setStatus(`${built.length} élève(s) chargé(s) depuis Supabase.`);setLoading(false)})()},[orgId,classId,yearId,periodId,sb])

 const resolve=(text:string,s:Student)=>text.replaceAll('{{school_name}}','NOM DE L’ÉTABLISSEMENT').replaceAll('{{student_name}}',s.name).replaceAll('{{student_number}}',s.number).replaceAll('{{class_name}}',className).replaceAll('{{academic_year}}',yearName).replaceAll('{{period}}',period).replaceAll('{{general_average}}',s.average.toFixed(2)).replaceAll('{{rank}}',String(s.rank)).replaceAll('{{appreciation}}',s.average>=14?'Très bon travail':s.average>=10?'Travail satisfaisant':'Encouragements à poursuivre les efforts').replaceAll('{{school_logo}}','LOGO ÉCOLE').replaceAll('{{student_photo}}','PHOTO ÉLÈVE')
 const printableMarkup=(s:Student)=>{const blocks=template.blocks.map(b=>{let content=resolve(b.text,s);if(b.type==='grades_table')content=`<table class="grades"><thead><tr><th>Matière</th><th>Interro.</th><th>Devoirs</th><th>Contrôles</th><th>Examen</th><th>Moyenne</th><th>Coef.</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${r.subject}</td><td>${r.interrogations}</td><td>${r.devoirs}</td><td>${r.controles}</td><td>${r.examen}</td><td>${r.average.toFixed(2)}</td><td>${r.coefficient}</td></tr>`).join('')}</tbody></table>`;if(b.type==='school_logo')content='<div class="logo">LOGO ÉCOLE</div>';if(b.type==='student_photo')content='<div class="photo">PHOTO</div>';return`<div class="block block-${b.type}" style="left:${b.x}px;top:${b.y}px;width:${b.width}px;height:${b.height}px;font-size:${b.fontSize}px;opacity:${b.opacity}">${content}</div>`}).join('');return`<section class="paper">${blocks}</section>`}
 const printOne=(s:Student)=>{const w=window.open('','_blank','noopener,noreferrer');if(!w){setStatus('Autorisez les fenêtres contextuelles.');return}w.document.write(`<!doctype html><html><head><title>Bulletin - ${s.name}</title><style>${printCss()}</style></head><body>${printableMarkup(s)}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
 const generateAll=()=>{if(!students.length){setStatus('Aucun bulletin à générer.');return}const w=window.open('','_blank','noopener,noreferrer');if(!w){setStatus('Autorisez les fenêtres contextuelles.');return}w.document.write(`<!doctype html><html><head><title>Bulletins - ${className}</title><style>${printCss()}</style></head><body>${students.map(printableMarkup).join('<div class="page-break"></div>')}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
 const selectedMarkup=useMemo(()=>selected?printableMarkup(selected):'', [selected,template,className,period,yearName])
 return <main className="bulletins-page"><header className="grades-header"><div><a className="back-link" href="/dashboard">← Tableau de bord</a><p className="eyebrow">PÉDAGOGIE · BULLETINS</p><h1>Génération des bulletins</h1><p>Les résultats affichés proviennent des notes enregistrées dans Supabase.</p></div><button className="student-primary" onClick={generateAll} disabled={loading||!students.length}>Générer tous les bulletins</button></header><section className="grade-filters"><label>Année<select value={yearId} onChange={e=>{setYearId(e.target.value);const c=classes.find(x=>x.academic_year_id===e.target.value);if(c)setClassId(c.id);const p=periods.find(x=>x.academic_year_id===e.target.value);if(p)setPeriodId(p.id)}}>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Classe<select value={classId} onChange={e=>setClassId(e.target.value)}>{classes.filter(c=>c.academic_year_id===yearId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Période<select value={periodId} onChange={e=>setPeriodId(e.target.value)}>{periods.filter(p=>p.academic_year_id===yearId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="bulletin-summary"><b>{students.length}</b><span>élèves concernés</span></div></section>{status&&<div className="grade-message">{status}</div>}{loading?<div className="grade-message">Chargement…</div>:<section className="students-table-wrap"><table><thead><tr><th>Élève</th><th>Matricule</th><th>Moyenne générale</th><th>Rang</th><th>Action</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><b>{s.name}</b></td><td><code>{s.number}</code></td><td><strong>{s.average.toFixed(2)} / 20</strong></td><td>{s.rank}e</td><td><button className="student-secondary" onClick={()=>setSelected(s)}>Aperçu</button>{' '}<button className="student-primary" onClick={()=>printOne(s)}>PDF / Imprimer</button></td></tr>)}</tbody></table></section>}{selected&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setSelected(null)}><section className="student-modal bulletin-preview"><header><div><p className="eyebrow">APERÇU A4 · DONNÉES RÉELLES</p><h2>Bulletin — {selected.name}</h2></div><button className="modal-close" onClick={()=>setSelected(null)}>×</button></header><div dangerouslySetInnerHTML={{__html:selectedMarkup}}/><footer><button className="student-secondary" onClick={()=>setSelected(null)}>Fermer</button><button className="student-primary" onClick={()=>printOne(selected)}>Générer / Exporter PDF</button></footer></section></div>}</main>}

function printCss(){return`.paper{position:relative;width:794px;height:1123px;background:#fff;margin:0 auto;box-sizing:border-box;overflow:hidden;color:#172033;font-family:Arial,sans-serif}.block{position:absolute;box-sizing:border-box;overflow:hidden}.block-heading{font-weight:700;text-align:center}.block-student_info{padding:12px;border:1px solid #d8dee9;border-radius:6px}.block-grades_table{overflow:visible}.grades{width:100%;border-collapse:collapse;font-size:10px}.grades th,.grades td{border:1px solid #cbd3df;padding:7px 5px;text-align:center}.grades th{font-weight:700;background:#edf2f8}.grades th:first-child,.grades td:first-child{text-align:left}.logo{width:76px;height:58px;border:2px dashed #8a97aa;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700}.photo{width:68px;height:78px;border:1px solid #9aa5b5;display:flex;align-items:center;justify-content:center;font-size:9px}.block-watermark{transform:rotate(-18deg);display:flex;align-items:center;justify-content:center;font-weight:800;color:#30466b}.block-average{font-weight:800;padding:8px;text-align:right}.block-rank{font-weight:700;padding:8px;text-align:right}.block-signature{border-top:1px solid #8d98a8;padding-top:12px}.page-break{page-break-after:always}.page-break:last-child{page-break-after:auto}@page{size:A4 portrait;margin:0}body{margin:0;background:#fff}`}
