'use client'
import {useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type C={id:string;name:string;code?:string|null;academic_year_id:string}; type Y={id:string;name:string;is_current:boolean}; type S={id:string;name:string;code?:string|null;coefficient:number}; type Sem={id:string;name:string;academic_year_id:string;semester_number:number}; type St={id:string;first_name:string;last_name:string;student_number:string}; type G={id:string;student_id:string;value:number|null;comment:string|null}
export default function GradeManager({organizationId,classes,years,subjects,semesters}:{organizationId:string;classes:C[];years:Y[];subjects:S[];semesters:Sem[]}){
 const [year,setYear]=useState(years.find(y=>y.is_current)?.id||years[0]?.id||''),[classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState(''),[semesterId,setSemesterId]=useState(''),[type,setType]=useState('control'),[title,setTitle]=useState(''),[max,setMax]=useState('20'),[coef,setCoef]=useState('1'),[students,setStudents]=useState<St[]>([]),[grades,setGrades]=useState<Record<string,G>>({}),[assessmentId,setAssessmentId]=useState(''),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false)
 const classOptions=useMemo(()=>classes.filter(c=>c.academic_year_id===year),[classes,year]); const semOptions=useMemo(()=>semesters.filter(s=>s.academic_year_id===year),[semesters,year])
 const load=async()=>{setMsg('');if(!classId||!subjectId){setMsg('Choisissez une classe et une matière.');return} const sb=createClient(); const {data:ass}=await sb.from('assessments').select('id,title,max_value,coefficient,assessment_type').eq('organization_id',organizationId).eq('class_group_id',classId).eq('subject_id',subjectId).eq('academic_year_id',year).eq('semester_id',semesterId||null).order('created_at',{ascending:false}).limit(1).maybeSingle(); if(ass){setAssessmentId(ass.id);setTitle(ass.title);setMax(String(ass.max_value));setCoef(String(ass.coefficient));setType(ass.assessment_type)} else setAssessmentId(''); const {data:rows}=await sb.from('student_class_assignments').select('enrollment_id,class_group_id,student_enrollments!inner(student_id,academic_year_id,status,students!inner(id,first_name,last_name,student_number))').eq('organization_id',organizationId).eq('class_group_id',classId).eq('status','active').eq('student_enrollments.academic_year_id',year); const st=(rows??[]).map((r:any)=>r.student_enrollments.students).filter(Boolean);setStudents(st);if(ass){const {data:g}=await sb.from('grades').select('id,student_id,value,comment').eq('assessment_id',ass.id);setGrades(Object.fromEntries((g??[]).map((x:G)=>[x.student_id,x])))}else setGrades({});setMsg(`${st.length} élève(s) chargé(s).`)}
 const save=async()=>{setMsg('');if(!classId||!subjectId||!title){setMsg('Classe, matière et intitulé sont obligatoires.');return}setSaving(true);try{const sb=createClient();let aid=assessmentId;if(!aid){const {data,e}=await sb.rpc('create_assessment',{p_organization_id:organizationId,p_subject_id:subjectId,p_class_group_id:classId,p_academic_year_id:year,p_title:title,p_assessment_type:type,p_max_value:Number(max),p_coefficient:Number(coef),p_semester_id:semesterId||null});if(e)throw e;aid=data.id;setAssessmentId(aid)}for(const st of students){const g=grades[st.id];if(g?.value!==undefined){const {data,e}=await sb.rpc('save_grade',{p_organization_id:organizationId,p_assessment_id:aid,p_student_id:st.id,p_value:g.value,p_comment:g.comment||null});if(e)throw e;setGrades(x=>({...x,[st.id]:data}))}}setMsg('Notes enregistrées avec succès.')}catch(e){setMsg(e instanceof Error?e.message:'Erreur lors de l’enregistrement.')}finally{setSaving(false)}}
 return <main className="grades-page"><header className="grades-header"><div><a className="back-link" href="/dashboard">← Tableau de bord</a><p className="eyebrow">PÉDAGOGIE</p><h1>Saisie des notes</h1><p>Les listes sont chargées à partir des élèves réellement affectés à la classe.</p></div><button className="student-primary" onClick={save} disabled={saving}>{saving?'Enregistrement…':'Enregistrer les notes'}</button></header>
 <section className="grade-filters"><label>Année<select value={year} onChange={e=>{setYear(e.target.value);setClassId('');setStudents([])}}>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Classe<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Sélectionner</option>{classOptions.map(c=><option key={c.id} value={c.id}>{c.name}{c.code?` (${c.code})`:''}</option>)}</select></label><label>Matière<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Sélectionner</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}{s.code?` (${s.code})`:''}</option>)}</select></label><label>Période<select value={semesterId} onChange={e=>setSemesterId(e.target.value)}><option value="">Toutes</option>{semOptions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Évaluation<select value={type} onChange={e=>setType(e.target.value)}><option value="control">Contrôle</option><option value="devoir">Devoir</option><option value="exam">Examen</option><option value="partial">Partiel</option></select></label><button className="student-secondary" onClick={load}>Charger</button></section>
 <section className="assessment-config"><label>Intitulé de l’évaluation<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Devoir surveillé 1"/></label><label>Barème<input type="number" min="1" value={max} onChange={e=>setMax(e.target.value)}/></label><label>Coefficient<input type="number" min="0.5" step="0.5" value={coef} onChange={e=>setCoef(e.target.value)}/></label></section>{msg&&<div className="grade-message">{msg}</div>}
 <section className="grades-table-wrap"><table><thead><tr><th>#</th><th>Élève</th><th>Matricule</th><th>Note / {max}</th><th>Coefficient</th><th>Statut</th></tr></thead><tbody>{students.map((s,i)=>{const g=grades[s.id];return <tr key={s.id}><td>{i+1}</td><td><b>{s.first_name} {s.last_name}</b></td><td><code>{s.student_number}</code></td><td><input className="grade-input" type="number" min="0" max={max} step="0.25" value={g?.value??''} onChange={e=>setGrades(x=>({...x,[s.id]:{id:g?.id||'',student_id:s.id,value:e.target.value===''?null:Number(e.target.value),comment:g?.comment||null}}))}/></td><td>{coef}</td><td>{g?.value==null?'Non saisie':'Saisie'}</td></tr>)}{!students.length&&<tr><td colSpan={6}><div className="students-empty"><strong>Aucun élève à afficher</strong><span>Sélectionnez une année, une classe et une matière puis cliquez sur Charger.</span></div></td></tr>}</tbody></table></section></main>
}
