'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

const steps=['Identité','Coordonnées','Formation','Documents','Récapitulatif'];
type Row=Record<string,any>;

export default function ApplicationForm(){
 const supabase=createClient();
 const [step,setStep]=useState(0),[submitted,setSubmitted]=useState(false),[saving,setSaving]=useState(false),[number,setNumber]=useState('');
 const [org,setOrg]=useState<Row|null>(null),[programs,setPrograms]=useState<Row[]>([]),[levels,setLevels]=useState<Row[]>([]),[requirements,setRequirements]=useState<Row[]>([]);
 const [data,setData]=useState({firstName:'',lastName:'',sex:'',birthDate:'',phone:'',email:'',address:'',parentName:'',parentPhone:'',programId:'',levelId:''});
 const [files,setFiles]=useState<Record<string,File|null>>({});
 useEffect(()=>{(async()=>{const {data:o}=await supabase.from('organizations').select('*').limit(1).maybeSingle(); if(o){setOrg(o); const [{data:p},{data:l},{data:r}]=await Promise.all([supabase.from('programs').select('id,name,code').eq('organization_id',o.id).eq('is_active',true).order('name'),supabase.from('levels').select('id,name,code').eq('organization_id',o.id).eq('is_active',true).order('ordinal'),supabase.from('admission_document_requirements').select('*').eq('organization_id',o.id).eq('active',true).eq('applies_to','admission').order('sort_order')]);setPrograms(p??[]);setLevels(l??[]);setRequirements(r??[]);}})()},[]);
 const update=(k:string,v:string)=>setData(d=>({...d,[k]:v}));
 const next=()=>setStep(s=>Math.min(4,s+1)),back=()=>setStep(s=>Math.max(0,s-1));
 async function submit(e:FormEvent){e.preventDefault();if(!org)return alert('Établissement indisponible.');setSaving(true);try{const year=(await supabase.from('academic_years').select('id').eq('organization_id',org.id).eq('is_current',true).maybeSingle()).data;const applicationNumber=`ADM-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;const {data:a,error}=await supabase.from('admission_applications').insert({organization_id:org.id,academic_year_id:year?.id??null,application_number:applicationNumber,first_name:data.firstName,last_name:data.lastName,sex:data.sex||null,date_of_birth:data.birthDate||null,phone:data.phone,email:data.email||null,address:data.address||null,parent_name:data.parentName||null,parent_phone:data.parentPhone||null,program_id:data.programId||null,level_id:data.levelId||null}).select().single();if(error)throw error;for(const r of requirements){const f=files[r.id];if(!f)continue;const path=`${org.id}/${a.id}/${r.id}-${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('admission-documents').upload(path,f,{contentType:f.type,upsert:false});if(up.error)throw up.error;const ins=await supabase.from('admission_application_documents').insert({application_id:a.id,requirement_id:r.id,file_path:path,original_name:f.name,mime_type:f.type,file_size:f.size});if(ins.error)throw ins.error;}setNumber(applicationNumber);setSubmitted(true)}catch(err:any){alert(err?.message||'Erreur lors de la soumission.')}finally{setSaving(false)}}
 if(submitted)return <main className="min-h-screen bg-slate-50 px-6 py-16"><div className="mx-auto max-w-xl rounded-3xl border bg-white p-8 text-center shadow-sm"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-green-100 text-2xl">✓</div><h1 className="text-2xl font-bold">Candidature envoyée</h1><p className="mt-3 text-slate-600">Conservez précieusement votre numéro de candidature.</p><p className="mt-4 rounded-xl bg-slate-100 p-4 text-xl font-bold">{number}</p><Link href="/apply" className="mt-6 inline-flex rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Retour</Link></div></main>;
 return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-3xl"><Link href="/apply" className="text-sm text-blue-600">← Admissions</Link><h1 className="mt-3 text-3xl font-bold">Votre candidature</h1><div className="mt-6 flex gap-2">{steps.map((s,i)=><div key={s} className="flex-1"><div className={`h-1.5 rounded-full ${i<=step?'bg-slate-900':'bg-slate-200'}`}/><p className="mt-2 hidden text-xs sm:block">{i+1}. {s}</p></div>)}</div>
 <form onSubmit={submit} className="mt-8 rounded-3xl border bg-white p-6 shadow-sm md:p-8">
 {step===0&&<section className="space-y-5"><h2 className="text-xl font-semibold">Identité</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Prénom *" value={data.firstName} onChange={v=>update('firstName',v)}/><Field label="Nom *" value={data.lastName} onChange={v=>update('lastName',v)}/><Field label="Date de naissance" type="date" value={data.birthDate} onChange={v=>update('birthDate',v)}/><Select label="Sexe" value={data.sex} onChange={v=>update('sex',v)} options={['Femme','Homme']}/></div></section>}
 {step===1&&<section className="space-y-5"><h2 className="text-xl font-semibold">Coordonnées</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Téléphone *" value={data.phone} onChange={v=>update('phone',v)}/><Field label="Email" type="email" value={data.email} onChange={v=>update('email',v)}/><div className="md:col-span-2"><Field label="Adresse" value={data.address} onChange={v=>update('address',v)}/></div><Field label="Parent / tuteur" value={data.parentName} onChange={v=>update('parentName',v)}/><Field label="Téléphone du parent" value={data.parentPhone} onChange={v=>update('parentPhone',v)}/></div></section>}
 {step===2&&<section className="space-y-5"><h2 className="text-xl font-semibold">Formation souhaitée</h2><div className="grid gap-4 md:grid-cols-2"><Select label="Filière *" value={data.programId} onChange={v=>update('programId',v)} options={programs.map(p=>p.id)} optionLabels={Object.fromEntries(programs.map(p=>[p.id,`${p.name}${p.code?' ('+p.code+')':''}`]))}/><Select label="Niveau *" value={data.levelId} onChange={v=>update('levelId',v)} options={levels.map(l=>l.id)} optionLabels={Object.fromEntries(levels.map(l=>[l.id,`${l.name}${l.code?' ('+l.code+')':''}`]))}/></div>{programs.length===0&&<p className="text-sm text-amber-700">Aucune filière ouverte n'est actuellement configurée.</p>}</section>}
 {step===3&&<section className="space-y-5"><h2 className="text-xl font-semibold">Pièces du dossier</h2>{requirements.length===0?<p className="rounded-xl border p-4 text-sm">Aucune pièce configurée par l'établissement.</p>:requirements.map(r=><label key={r.id} className="block rounded-xl border p-4 text-sm"><span className="font-medium">{r.name}{r.required?' *':' (facultatif)'}</span>{r.description&&<span className="mt-1 block text-xs text-slate-500">{r.description}</span>}<input required={r.required} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="mt-2 block w-full" onChange={e=>setFiles(f=>({...f,[r.id]:e.target.files?.[0]??null}))}/></label>)}</section>}
 {step===4&&<section className="space-y-5"><h2 className="text-xl font-semibold">Récapitulatif</h2><div className="grid gap-2 rounded-2xl bg-slate-50 p-5 text-sm"><p><b>Nom :</b> {data.firstName} {data.lastName}</p><p><b>Téléphone :</b> {data.phone}</p><p><b>Formation :</b> {programs.find(p=>p.id===data.programId)?.name||'—'} — {levels.find(l=>l.id===data.levelId)?.name||'—'}</p><p><b>Documents :</b> {Object.values(files).filter(Boolean).length}/{requirements.filter(r=>r.required).length} requis sélectionnés</p></div><label className="flex gap-3 text-sm"><input required type="checkbox"/> Je certifie l'exactitude des informations fournies.</label></section>}
 <div className="mt-8 flex justify-between gap-3 border-t pt-5"><button type="button" onClick={back} disabled={step===0} className="rounded-xl border px-5 py-3 disabled:opacity-40">Précédent</button>{step<4?<button type="button" onClick={next} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Continuer</button>:<button disabled={saving} type="submit" className="rounded-xl bg-green-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?'Envoi...':'Soumettre ma candidature'}</button>}</div></form></div></main>
}
function Field({label,value,onChange,type='text'}:{label:string,value:string,onChange:(v:string)=>void,type?:string}){return <label className="text-sm">{label}<input required={label.includes('*')} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label>}
function Select({label,value,onChange,options,optionLabels}:{label:string,value:string,onChange:(v:string)=>void,options:string[],optionLabels?:Record<string,string>}){return <label className="text-sm">{label}<select required={label.includes('*')} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">Sélectionner</option>{options.map(o=><option key={o} value={o}>{optionLabels?.[o]??o}</option>)}</select></label>}
