'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';

const steps=['Identité','Coordonnées','Formation','Documents','Récapitulatif'];

export default function ApplicationForm(){
 const [step,setStep]=useState(0); const [submitted,setSubmitted]=useState(false);
 const [data,setData]=useState({firstName:'',lastName:'',sex:'',birthDate:'',phone:'',email:'',address:'',parentName:'',parentPhone:'',program:'',level:''});
 const [files,setFiles]=useState<Record<string,File|null>>({});
 const update=(k:string,v:string)=>setData(d=>({...d,[k]:v}));
 const next=()=>setStep(s=>Math.min(4,s+1)); const back=()=>setStep(s=>Math.max(0,s-1));
 const submit=(e:FormEvent)=>{e.preventDefault();setSubmitted(true)};
 if(submitted)return <main className="min-h-screen bg-slate-50 px-6 py-16"><div className="mx-auto max-w-xl rounded-3xl border bg-white p-8 text-center shadow-sm"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-green-100 text-2xl">✓</div><h1 className="text-2xl font-bold">Candidature enregistrée</h1><p className="mt-3 text-slate-600">Votre numéro de candidature sera affiché ici après la connexion à Supabase.</p><Link href="/apply" className="mt-6 inline-flex rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Retour</Link></div></main>;
 return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-3xl"><div className="mb-8"><Link href="/apply" className="text-sm text-blue-600">← Admissions</Link><h1 className="mt-3 text-3xl font-bold text-slate-900">Votre candidature</h1><div className="mt-6 flex gap-2">{steps.map((s,i)=><div key={s} className="flex-1"><div className={`h-1.5 rounded-full ${i<=step?'bg-slate-900':'bg-slate-200'}`}/><p className="mt-2 hidden text-xs sm:block">{i+1}. {s}</p></div>)}</div></div>
 <form onSubmit={submit} className="rounded-3xl border bg-white p-6 shadow-sm md:p-8">
 {step===0&&<section className="space-y-5"><h2 className="text-xl font-semibold">Identité</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Prénom *" value={data.firstName} onChange={v=>update('firstName',v)}/><Field label="Nom *" value={data.lastName} onChange={v=>update('lastName',v)}/><Field label="Date de naissance" type="date" value={data.birthDate} onChange={v=>update('birthDate',v)}/><label className="text-sm">Sexe<select value={data.sex} onChange={e=>update('sex',e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">Sélectionner</option><option>Femme</option><option>Homme</option></select></label></div></section>}
 {step===1&&<section className="space-y-5"><h2 className="text-xl font-semibold">Coordonnées</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Téléphone *" value={data.phone} onChange={v=>update('phone',v)}/><Field label="Email" type="email" value={data.email} onChange={v=>update('email',v)}/><div className="md:col-span-2"><Field label="Adresse" value={data.address} onChange={v=>update('address',v)}/></div><Field label="Parent / tuteur" value={data.parentName} onChange={v=>update('parentName',v)}/><Field label="Téléphone du parent" value={data.parentPhone} onChange={v=>update('parentPhone',v)}/></div></section>}
 {step===2&&<section className="space-y-5"><h2 className="text-xl font-semibold">Formation souhaitée</h2><p className="text-sm text-slate-600">Les filières affichées seront alimentées par les formations ouvertes de l'établissement.</p><div className="grid gap-4 md:grid-cols-2"><Field label="Filière *" value={data.program} onChange={v=>update('program',v)}/><Field label="Niveau *" value={data.level} onChange={v=>update('level',v)}/></div></section>}
 {step===3&&<section className="space-y-5"><h2 className="text-xl font-semibold">Pièces du dossier</h2><p className="text-sm text-slate-600">Les pièces ci-dessous seront remplacées automatiquement par celles configurées par l'école.</p>{['Diplôme / BAC','Relevé de notes','Acte de naissance','Photo d’identité'].map(name=><label key={name} className="block rounded-xl border p-4 text-sm"><span className="font-medium">{name} *</span><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="mt-2 block w-full" onChange={e=>setFiles(f=>({...f,[name]:e.target.files?.[0]??null}))}/></label>)}</section>}
 {step===4&&<section className="space-y-5"><h2 className="text-xl font-semibold">Récapitulatif</h2><div className="grid gap-2 rounded-2xl bg-slate-50 p-5 text-sm"><p><b>Nom :</b> {data.firstName} {data.lastName}</p><p><b>Téléphone :</b> {data.phone}</p><p><b>Email :</b> {data.email||'—'}</p><p><b>Formation :</b> {data.program||'—'} — {data.level||'—'}</p><p><b>Documents :</b> {Object.values(files).filter(Boolean).length} fichier(s) sélectionné(s)</p></div><label className="flex gap-3 text-sm"><input required type="checkbox"/> Je certifie l'exactitude des informations fournies.</label></section>}
 <div className="mt-8 flex justify-between gap-3 border-t pt-5"><button type="button" onClick={back} disabled={step===0} className="rounded-xl border px-5 py-3 disabled:opacity-40">Précédent</button>{step<4?<button type="button" onClick={next} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Continuer</button>:<button type="submit" className="rounded-xl bg-green-600 px-5 py-3 font-semibold text-white">Soumettre ma candidature</button>}</div>
 </form></div></main>
}
function Field({label,value,onChange,type='text'}:{label:string,value:string,onChange:(v:string)=>void,type?:string}){return <label className="text-sm">{label}<input required={label.includes('*')} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border p-3 outline-none focus:ring-2"/></label>}
