'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

type Application = Record<string, any>;
type Document = Record<string, any>;

const statusLabel: Record<string,string> = { pending:'En attente de vérification', under_review:'Dossier en cours de vérification', incomplete:'Documents à compléter', accepted:'Candidature acceptée', rejected:'Candidature refusée' };

export default function TrackApplication(){
 const supabase=createClient(); const [number,setNumber]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [application,setApplication]=useState<Application|null>(null); const [documents,setDocuments]=useState<Document[]>([]);
 async function search(e:FormEvent){e.preventDefault();setError('');setApplication(null);setDocuments([]);setLoading(true);const {data,error}=await supabase.from('admission_applications').select('id,application_number,first_name,last_name,status,created_at,reviewed_at,rejection_reason').eq('application_number',number.trim()).maybeSingle();if(error||!data){setError(error?.message||'Aucune candidature trouvée avec ce numéro.');setLoading(false);return;}const {data:docs}=await supabase.from('admission_application_documents').select('id,original_name,status,rejection_reason,created_at').eq('application_id',data.id).order('created_at');setApplication(data);setDocuments(docs??[]);setLoading(false);}
 return <main className="min-h-screen bg-slate-50 px-4 py-12"><div className="mx-auto max-w-2xl"><Link href="/apply" className="text-sm text-blue-600">← Admissions</Link><div className="mt-5 rounded-3xl border bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">CONIK</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Suivre ma candidature</h1><p className="mt-3 text-slate-600">Saisissez votre numéro de candidature pour consulter l'état de votre dossier.</p><form onSubmit={search} className="mt-6 flex flex-col gap-3 sm:flex-row"><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="Ex. ADM-2026-123456" className="flex-1 rounded-xl border p-3"/><button disabled={loading} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-50">{loading?'Recherche...':'Rechercher'}</button></form>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
 {application&&<section className="mt-8 space-y-6"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-sm text-slate-500">Numéro</p><p className="text-xl font-bold">{application.application_number}</p><p className="mt-4 text-sm text-slate-500">Candidat</p><p className="font-semibold">{application.first_name} {application.last_name}</p><div className="mt-4 inline-flex rounded-full border px-3 py-1 text-sm font-medium">{statusLabel[application.status]??application.status}</div></div><div><h2 className="font-semibold">Documents</h2>{documents.length===0?<p className="mt-3 text-sm text-slate-500">Aucun document enregistré.</p>:<div className="mt-3 space-y-2">{documents.map(d=><div key={d.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><span className="font-medium">{d.original_name}</span><span className="text-sm">{d.status==='verified'?'✓ Vérifié':d.status==='rejected'?'✗ Rejeté':'À vérifier'}</span></div>{d.rejection_reason&&<p className="mt-2 text-sm text-red-600">Motif : {d.rejection_reason}</p>}</div>)}</div>}</div>{application.rejection_reason&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700"><b>Motif :</b> {application.rejection_reason}</div>}</section>}</div></div></main>;
}
