'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

type Row={id:string;name:string;code?:string|null;is_active?:boolean;ordinal?:number};
export default function Academic(){const sb=createClient();const [programs,setPrograms]=useState<Row[]>([]);const [levels,setLevels]=useState<Row[]>([]);const [subjects,setSubjects]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [tab,setTab]=useState<'programs'|'levels'|'subjects'>('programs');
async function load(){setLoading(true);const org=(await sb.from('organizations').select('id').limit(1).maybeSingle()).data;if(!org){setLoading(false);return}const [{data:p},{data:l},{data:s}]=await Promise.all([sb.from('programs').select('id,name,code,is_active').eq('organization_id',org.id).order('name'),sb.from('levels').select('id,name,code,is_active,ordinal').eq('organization_id',org.id).order('ordinal'),sb.from('subjects').select('id,name,code,is_active').eq('organization_id',org.id).order('name')]);setPrograms(p||[]);setLevels(l||[]);setSubjects(s||[]);setLoading(false)}useEffect(()=>{load()},[]);
const items=tab==='programs'?programs:tab==='levels'?levels:subjects;return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-5 py-8"><Link href="/admin" className="text-sm text-blue-600">← Administration</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black tracking-widest text-blue-600">CONIK • ACADÉMIQUE</p><h1 className="mt-1 text-3xl font-bold">Structure académique</h1><p className="mt-2 text-sm text-slate-500">Une seule structure alimentera ensuite les inscriptions, affectations et notes.</p></div><button onClick={load} className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Actualiser</button></div><div className="mt-8 flex gap-2 overflow-x-auto">{[['programs','Filières'],['levels','Niveaux'],['subjects','Matières']].map(([id,label])=><button key={id} onClick={()=>setTab(id as any)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===id?'bg-slate-900 text-white':'border bg-white'}`}>{label}</button>)}</div><section className="mt-4 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid grid-cols-[1fr_150px_120px] border-b bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-slate-500"><span>Nom</span><span>Code</span><span>Statut</span></div>{loading?<p className="p-8 text-sm text-slate-500">Chargement…</p>:items.length===0?<p className="p-8 text-sm text-slate-500">Aucune donnée configurée pour le moment.</p>:items.map(x=><div key={x.id} className="grid grid-cols-[1fr_150px_120px] items-center border-b px-5 py-4 text-sm last:border-0"><span className="font-medium">{x.name}</span><span className="text-slate-500">{x.code||'—'}</span><span><span className={`rounded-full px-2 py-1 text-xs font-semibold ${x.is_active===false?'bg-slate-100 text-slate-500':'bg-green-50 text-green-700'}`}>{x.is_active===false?'Inactif':'Actif'}</span></span></div>)}</section></div></main>}
