'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '../../lib/supabase/client'
import { isDesktopRuntime, localRuntime, LOCAL_INSTITUTION_ID_KEY } from '../../lib/local/tauri'

const initial={name:'',slug:'',email:'',phone:'',address:'',city:'',logoUrl:'',academicYear:'2026-2027',currency:'XOF',username:'admin',password:'',firstName:'',lastName:'',adminPhone:''}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
export default function OnboardingPage(){
 const router=useRouter(); const [form,setForm]=useState(initial); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(false); const [desktop,setDesktop]=useState(false); const [ready,setReady]=useState(false)
 useEffect(()=>{if(!isDesktopRuntime()){setReady(true);return}setDesktop(true);setStatus('Initialisation du stockage local…');localRuntime.initialize().then(async()=>{const id=localStorage.getItem(LOCAL_INSTITUTION_ID_KEY);if(!id){setStatus('Mode hors ligne prêt. Configurez votre établissement et son administrateur.');return}const [institution,admin,settings]=await Promise.all([localRuntime.getInstitution(id),localRuntime.getAdmin(id),localRuntime.getSettings(id)]);if(!institution){localStorage.removeItem(LOCAL_INSTITUTION_ID_KEY);setStatus('Mode hors ligne prêt. Configurez votre établissement et son administrateur.');return}setForm(v=>({...v,name:institution.name,slug:institution.slug,email:institution.email??'',phone:institution.phone??'',address:institution.address??'',city:institution.city??'',logoUrl:institution.logo_path??'',academicYear:settings?.academic_year_label??institution.academic_year_label??v.academicYear,currency:settings?.currency_code??v.currency,username:admin?.username??v.username,firstName:admin?.first_name??'',lastName:admin?.last_name??'',adminPhone:admin?.phone??''}));setStatus(admin?`Configuration locale récupérée : ${institution.name} · administrateur ${admin.username}`:`Établissement récupéré localement : ${institution.name}. Créez maintenant l'administrateur.`)}).catch(e=>setStatus(e instanceof Error?e.message:String(e))).finally(()=>setReady(true))},[])
 const set=(k:keyof typeof initial,v:string)=>setForm(x=>({...x,[k]:v}))
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);try{if(desktop){setStatus('Enregistrement local sécurisé…');const institution=await localRuntime.createInstitution({name:form.name,slug:form.slug||slugify(form.name),country_code:'TG',timezone:'Africa/Lome',email:form.email||undefined,phone:form.phone||undefined,address:form.address||undefined,city:form.city||undefined,logo_path:form.logoUrl||undefined,academic_year_label:form.academicYear||undefined});await localRuntime.bootstrapAdmin({institution_id:institution.id,username:form.username,password:form.password,first_name:form.firstName,last_name:form.lastName,phone:form.adminPhone||undefined});await localRuntime.updateSettings({institution_id:institution.id,currency_code:form.currency,locale:'fr-FR',country_code:'TG',timezone:'Africa/Lome',academic_year_label:form.academicYear||undefined});localStorage.setItem(LOCAL_INSTITUTION_ID_KEY,institution.id);setStatus(`Configuration terminée hors ligne : ${institution.name}. Administrateur local créé.`);setForm(v=>({...v,password:''}));return}
 const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Votre session a expiré. Veuillez vous reconnecter.');const {data,error}=await supabase.rpc('create_school_for_current_user',{p_name:form.name,p_slug:form.slug||slugify(form.name),p_email:form.email||null,p_phone:form.phone||null,p_address:form.address||null,p_city:form.city||null,p_logo_url:form.logoUrl||null});if(error)throw error;if(!data)throw new Error('L’établissement n’a pas pu être créé.');router.replace('/dashboard');router.refresh()}catch(err:any){setStatus(err?.message||'Impossible de terminer la configuration.')}finally{setLoading(false)}}
 const fields:[keyof typeof initial,string,boolean][]=[['name','Nom de l’établissement',true],['slug','Identifiant local',false],['email','Email',false],['phone','Téléphone',false],['address','Adresse',false],['city','Ville',false],['logoUrl','Chemin / URL du logo',false],['academicYear','Année académique',true],['currency','Devise',true],['firstName','Prénom de l’administrateur',true],['lastName','Nom de l’administrateur',true],['username','Identifiant administrateur',true]]
 return <main><div className="card"><div className="top"><p>CONIK · PREMIÈRE CONFIGURATION</p>{desktop&&<span>● HORS LIGNE</span>}</div><h1>{desktop?'Configurer CONIK':'Créer votre établissement'}</h1><p className="intro">{desktop?'Tout ce qui est opérationnel sera enregistré localement sur cet ordinateur.':'Votre établissement sera créé et associé à votre compte administrateur.'}</p><form onSubmit={submit}>{fields.map(([k,l,r])=><label key={k}>{l}{k==='currency'?<select value={form[k]} onChange={e=>set(k,e.target.value)}><option value="XOF">XOF — Franc CFA</option><option value="GHS">GHS — Cedi</option><option value="NGN">NGN — Naira</option><option value="USD">USD — Dollar</option></select>:<input required={r} value={form[k]} onChange={e=>set(k,e.target.value)}/>}</label>)}{desktop&&<><label>Mot de passe administrateur<input required minLength={8} type="password" value={form.password} onChange={e=>set('password',e.target.value)} placeholder="8 caractères minimum"/></label><label>Téléphone administrateur<input value={form.adminPhone} onChange={e=>set('adminPhone',e.target.value)}/></label></>}<button disabled={loading||!ready}>{loading?'Enregistrement…':!ready?'Initialisation…':desktop?'Enregistrer et terminer':'Créer mon établissement'}</button></form>{status&&<div className="status">{status}</div>}</div><style jsx>{`main{min-height:100vh;display:grid;place-items:center;padding:24px;background:#f8fafc;font-family:Inter,system-ui;color:#0f172a}.card{width:min(680px,100%);background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:32px;box-shadow:0 15px 40px #0f17200d}.top{display:flex;justify-content:space-between;align-items:center}.top p{font-size:11px;font-weight:800;letter-spacing:2px}.top span{font-size:11px;font-weight:800;color:#166534;background:#dcfce7;padding:6px 9px;border-radius:999px}.intro{color:#64748b;line-height:1.6}form{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-top:24px}label{font-weight:650;font-size:14px}label:first-child,label:nth-child(5),label:nth-child(7){grid-column:1/-1}input,select{display:block;width:100%;box-sizing:border-box;margin-top:7px;padding:12px 13px;border:1px solid #cbd5e1;border-radius:10px;font:inherit;background:#fff}button{grid-column:1/-1;margin-top:8px;padding:13px;border:0;border-radius:10px;background:#0f172a;color:#fff;font-weight:700;cursor:pointer}button:disabled{opacity:.6}.status{margin-top:18px;padding:12px;border-radius:10px;background:#f1f5f9;color:#334155}@media(max-width:640px){form{grid-template-columns:1fr}label,label:first-child,label:nth-child(5),label:nth-child(7),button{grid-column:auto}}`}</style></main>
}
