'use client'

import { useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Enrollment={id:string;student_id:string;academic_year_id:string;program_id:string;level_id:string;enrollment_number:string;status:string;enrollment_date:string}
type Student={id:string;student_number:string;first_name:string;last_name:string}
type Option={id:string;name:string;code?:string|null;is_current?:boolean}

export default function EnrollmentManager({organizationId,initialEnrollments,students,programs,levels,years}:{organizationId:string;initialEnrollments:Enrollment[];students:Student[];programs:Option[];levels:Option[];years:Option[]}){
 const [items,setItems]=useState(initialEnrollments),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({student_id:'',academic_year_id:years.find(y=>y.is_current)?.id||years[0]?.id||'',program_id:'',level_id:'',status:'active'})
 const student=(id:string)=>students.find(s=>s.id===id), program=(id:string)=>programs.find(p=>p.id===id), level=(id:string)=>levels.find(l=>l.id===id), year=(id:string)=>years.find(y=>y.id===id)
 const filtered=useMemo(()=>items.filter(i=>{const s=student(i.student_id);const q=search.toLowerCase().trim();return (!q||`${s?.first_name} ${s?.last_name} ${s?.student_number} ${i.enrollment_number}`.toLowerCase().includes(q))&&(status==='all'||i.status===status)}),[items,search,status,students])
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}))
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSaving(true);try{const sb=createClient();const {data,error}=await sb.rpc('create_enrollment',{p_organization_id:organizationId,p_student_id:form.student_id,p_academic_year_id:form.academic_year_id,p_program_id:form.program_id,p_level_id:form.level_id,p_status:form.status});if(error)throw error;setItems(x=>[data,...x]);setOpen(false)}catch(err){setError(err instanceof Error?err.message:'Impossible de créer l’inscription.')}finally{setSaving(false)}}
 return <main className="students-page"><header className="students-top"><div><a className="back-link" href="/dashboard">← Tableau de bord</a><p className="eyebrow">SCOLARITÉ</p><h1>Inscriptions</h1><p>Inscrivez les étudiants pour une année, une filière et un niveau.</p></div><button className="student-primary" onClick={()=>{setError('');setOpen(true)}}>+ Nouvelle inscription</button></header>
 <section className="student-toolbar"><div className="student-search"><span>⌕</span><input placeholder="Rechercher un étudiant ou un numéro…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous les statuts</option><option value="active">Actives</option><option value="cancelled">Annulées</option><option value="completed">Terminées</option></select><strong>{filtered.length} inscription{filtered.length!==1?'s':''}</strong></section>
 <section className="students-table-wrap"><table><thead><tr><th>Étudiant</th><th>N° inscription</th><th>Année</th><th>Filière</th><th>Niveau</th><th>Statut</th></tr></thead><tbody>{filtered.map(i=>{const s=student(i.student_id);return <tr key={i.id}><td><div className="student-name"><div>{s?.first_name?.charAt(0)}{s?.last_name?.charAt(0)}</div><span><b>{s?.first_name} {s?.last_name}</b><small>{s?.student_number}</small></span></div></td><td><code>{i.enrollment_number}</code></td><td>{year(i.academic_year_id)?.name||'—'}</td><td>{program(i.program_id)?.name||'—'}</td><td>{level(i.level_id)?.name||'—'}</td><td><span className={`status status-${i.status}`}>{i.status==='active'?'Active':i.status==='completed'?'Terminée':'Annulée'}</span></td></tr>})}{filtered.length===0&&<tr><td colSpan={6}><div className="students-empty"><strong>Aucune inscription trouvée</strong><span>Créez la première inscription pour cet établissement.</span></div></td></tr>}</tbody></table></section>
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setOpen(false)}><section className="student-modal"><header><div><p className="eyebrow">SCOLARITÉ</p><h2>Nouvelle inscription</h2></div><button type="button" className="modal-close" onClick={()=>setOpen(false)}>×</button></header><form onSubmit={save}><div className="form-grid"><label>Étudiant *<select required value={form.student_id} onChange={e=>set('student_id',e.target.value)}><option value="">Sélectionner</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} — {s.student_number}</option>)}</select></label><label>Année académique *<select required value={form.academic_year_id} onChange={e=>set('academic_year_id',e.target.value)}><option value="">Sélectionner</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?' · actuelle':''}</option>)}</select></label><label>Filière *<select required value={form.program_id} onChange={e=>set('program_id',e.target.value)}><option value="">Sélectionner</option>{programs.map(p=><option key={p.id} value={p.id}>{p.name}{p.code?` (${p.code})`:''}</option>)}</select></label><label>Niveau *<select required value={form.level_id} onChange={e=>set('level_id',e.target.value)}><option value="">Sélectionner</option>{levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div>{error&&<div className="form-error">{error}</div>}<footer><button type="button" className="student-secondary" onClick={()=>setOpen(false)}>Annuler</button><button disabled={saving} className="student-primary" type="submit">{saving?'Enregistrement…':'Créer l’inscription'}</button></footer></form></section></div>}
 </main>
}
