'use client'
import {useMemo,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type Grade={id:string;value:number;comment?:string;assessment_id:string};type Assessment={id:string;subject_id:string;title:string;assessment_type:string;max_value:number;coefficient:number;assessment_date?:string};type Subject={id:string;name:string;coefficient?:number};type Bulletin={id:string;template_id?:string;academic_year_id?:string;period:string;generated_at:string;template_version?:number;status?:string;payload?:any}
type Props={organizationId:string;student:any;documents:any[];enrollments:any[];years:any[];grades?:Grade[];assessments?:Assessment[];subjects?:Subject[];bulletins?:Bulletin[]}
export default function StudentDossier({student,documents,enrollments,years,organizationId,grades=[],assessments=[],subjects=[],bulletins=[]}:Props){
 const [tab,setTab]=useState<'overview'|'documents'|'history'|'notes'|'averages'|'bulletins'>('overview');const [docs,setDocs]=useState(documents);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null)
 const gradeRows=useMemo(()=>grades.map(g=>{const a=assessments.find(x=>x.id===g.assessment_id);const s=subjects.find(x=>x.id===a?.subject_id);const max=Number(a?.max_value||20);return {...g,assessment:a,subject:s,normalized:max>0?(Number(g.value)/max)*20:null}}),[grades,assessments,subjects]);const bySubject=useMemo(()=>{const map=new Map<string,{subject?:Subject;sum:number;weight:number;coefficient:number}>();for(const r of gradeRows){if(!r.subject||r.normalized===null)continue;const w=Number(r.assessment?.coefficient||1);const cur=map.get(r.subject.id)||{subject:r.subject,sum:0,weight:0,coefficient:Number(r.subject.coefficient||1)};cur.sum+=r.normalized*w;cur.weight+=w;map.set(r.subject.id,cur)}return[...map.values()].map(x=>({...x,average:x.weight?x.sum/x.weight:0}))},[gradeRows]);const general=useMemo(()=>{const c=bySubject.reduce((s,x)=>s+x.coefficient,0);return c?bySubject.reduce((s,x)=>s+x.average*x.coefficient,0)/c:0},[bySubject])
 async function upload(file:File){if(file.size>10*1024*1024){setMessage('Fichier trop volumineux (10 Mo maximum).');return}const allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){setMessage('Format non autorisé. PDF, JPG, PNG ou WebP.');return}setBusy(true);setMessage('Téléversement…');try{const s=createClient();const path=`${organizationId}/${student.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error:up}=await s.storage.from('student-documents').upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;const{data:row,error:db}=await s.from('student_documents').insert({organization_id:organizationId,student_id:student.id,file_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,title:file.name,category:'other'}).select('*').single();if(db)throw db;setDocs(d=>[row,...d]);setMessage('Document ajouté avec succès.')}catch(e:any){setMessage(e?.message||'Erreur pendant le téléversement.')}finally{setBusy(false)}}
 async function openDocument(d:any){const{data,error}=await createClient().storage.from('student-documents').createSignedUrl(d.file_path,300);if(error||!data?.signedUrl){setMessage('Impossible d’ouvrir ce document.');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')}async function removeDocument(d:any){if(!confirm(`Supprimer ${d.file_name||d.title||'ce document'} ?`))return;setBusy(true);try{const s=createClient();const{error:se}=await s.storage.from('student-documents').remove([d.file_path]);if(se)throw se;const{error:de}=await s.from('student_documents').delete().eq('id',d.id).eq('organization_id',organizationId);if(de)throw de;setDocs(ds=>ds.filter(x=>x.id!==d.id));setMessage('Document supprimé.')}catch(e:any){setMessage(e?.message||'Suppression impossible.')}finally{setBusy(false)}}
 const tabs=[['overview','Informations'],['documents','Documents'],['notes','Notes'],['averages','Moyennes'],['bulletins','Bulletins'],['history','Historique']] as const;const initials=`${student.first_name?.[0]||''}${student.last_name?.[0]||''}`.toUpperCase();const status=student.status==='active'?'Actif':student.status==='graduated'?'Diplômé':'Inactif'
 return <main className="student-dossier"><a className="back-link" href="/students">← Retour aux élèves</a><header className="student-dossier-header"><div className="dossier-identity"><div className="student-avatar-large">{initials}</div><div><p className="eyebrow">DOSSIER SCOLAIRE</p><h1>{student.first_name} {student.last_name}</h1><p><code>{student.student_number||'Matricule non renseigné'}</code> · <span className={`status status-${student.status}`}>{status}</span></p></div></div></header><nav className="student-tabs">{tabs.map(([key,label])=><button type="button" key={key} onClick={()=>setTab(key)} className={tab===key?'active':''}>{label}</button>)}</nav>
 {tab==='overview'&&<section className="dossier-panels"><article className="student-card"><h2>👤 Informations personnelles</h2><div className="dossier-details"><p><b>Nom complet</b>{student.first_name} {student.last_name}</p><p><b>Date de naissance</b>{student.date_of_birth||'—'}</p><p><b>Adresse</b>{student.address||'—'}</p></div></article><article className="student-card"><h2>📞 Contacts</h2><div className="dossier-details"><p><b>Téléphone</b>{student.phone||'—'}</p><p><b>Email</b>{student.email||'—'}</p><p><b>Parent / tuteur</b>{student.parent_name||'—'}</p></div></article></section>}
 {tab==='documents'&&<section className="student-card"><div className="document-header"><div><h2>📄 Documents</h2><p>Pièces administratives et scolaires de l’élève.</p></div><input ref={input} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/><button type="button" className="primary-action" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Traitement…':'+ Ajouter un document'}</button></div>{message&&<div className="dossier-message">{message}</div>}{docs.length?<ul className="dossier-list">{docs.map(d=><li key={d.id}><span><b>{d.file_name||d.title||'Document'}</b><small>{d.category||'Document'}{d.file_size?` · ${(d.file_size/1024/1024).toFixed(2)} Mo`:''}</small></span><span className="document-actions"><button type="button" onClick={()=>openDocument(d)}>Voir</button><button type="button" onClick={()=>removeDocument(d)} disabled={busy}>Supprimer</button></span></li>)}</ul>:<div className="dossier-empty"><strong>Aucun document enregistré</strong></div>}</section>}
 {tab==='notes'&&<section className="student-card"><h2>📝 Notes détaillées</h2>{gradeRows.length?<div className="table-wrap"><table><thead><tr><th>Matière</th><th>Évaluation</th><th>Type</th><th>Note</th><th>Barème</th><th>Coef.</th><th>Date</th></tr></thead><tbody>{gradeRows.map(r=><tr key={r.id}><td>{r.subject?.name||'—'}</td><td>{r.assessment?.title||'—'}</td><td>{r.assessment?.assessment_type||'—'}</td><td><strong>{Number(r.value).toFixed(2)}</strong></td><td>{Number(r.assessment?.max_value||20).toFixed(2)}</td><td>{Number(r.assessment?.coefficient||1).toFixed(2)}</td><td>{r.assessment?.assessment_date||'—'}</td></tr>)}</tbody></table></div>:<div className="dossier-empty"><strong>Aucune note enregistrée</strong></div>}</section>}
 {tab==='averages'&&<section className="student-card"><div className="section-title"><div><h2>📊 Moyennes</h2><p>Calcul pondéré à partir des notes enregistrées.</p></div><div className="general-average"><span>Moyenne générale</span><strong>{general.toFixed(2)} / 20</strong></div></div>{bySubject.length?<div className="table-wrap"><table><thead><tr><th>Matière</th><th>Moyenne /20</th><th>Coefficient</th></tr></thead><tbody>{bySubject.map(x=><tr key={x.subject?.id}><td><strong>{x.subject?.name}</strong></td><td>{x.average.toFixed(2)}</td><td>{x.coefficient.toFixed(2)}</td></tr>)}</tbody></table></div>:<div className="dossier-empty"><strong>Aucune moyenne calculable</strong></div>}</section>}
 {tab==='bulletins'&&<section className="student-card"><div className="section-title"><div><h2>📑 Historique des bulletins</h2><p>{bulletins.length} bulletin(s) enregistré(s).</p></div></div>{bulletins.length?<div className="table-wrap"><table><thead><tr><th>Période</th><th>Année</th><th>Version</th><th>Statut</th><th>Généré le</th></tr></thead><tbody>{bulletins.map(b=><tr key={b.id}><td><strong>{b.period||'—'}</strong></td><td>{years.find(y=>y.id===b.academic_year_id)?.name||'—'}</td><td>v{b.template_version??'—'}</td><td>{b.status||'generated'}</td><td>{new Date(b.generated_at).toLocaleString('fr-FR')}</td></tr>)}</tbody></table></div>:<div className="dossier-empty"><strong>Aucun bulletin généré</strong><span>Les bulletins générés pour cet élève apparaîtront ici.</span></div>}</section>}
 {tab==='history'&&<section className="student-card"><h2>🕐 Historique scolaire</h2>{enrollments.length?<ul className="dossier-list">{enrollments.map(e=><li key={e.id}><span><b>{e.enrollment_number||'Inscription'}</b><small>{years.find(y=>y.id===e.academic_year_id)?.name||'Année non renseignée'} · {e.status}</small></span><small>{e.enrollment_date||''}</small></li>)}</ul>:<div className="dossier-empty"><strong>Aucune inscription enregistrée</strong></div>}</section>}</main>
}