'use client'
import {useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'

type Tab='overview'|'documents'|'history'|'notes'|'averages'|'bulletins'
export default function StudentDossier({student,documents,enrollments,years,organizationId}:{organizationId:string;student:any;documents:any[];enrollments:any[];years:any[]}){
 const [tab,setTab]=useState<Tab>('overview'); const [docs,setDocs]=useState(documents); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const input=useRef<HTMLInputElement>(null)
 const tabs:[Tab,string][]=[['overview','Informations'],['documents','Documents'],['notes','Notes'],['averages','Moyennes'],['bulletins','Bulletins'],['history','Historique']]
 const initials=`${student.first_name?.[0]||''}${student.last_name?.[0]||''}`.toUpperCase(); const status=student.status==='active'?'Actif':student.status==='graduated'?'Diplômé':'Inactif'
 async function upload(file:File){ if(file.size>10*1024*1024){setMessage('Fichier trop volumineux (10 Mo maximum).');return} const allowed=['application/pdf','image/jpeg','image/png','image/webp']; if(!allowed.includes(file.type)){setMessage('Format non autorisé. PDF, JPG, PNG ou WebP.');return} setBusy(true);setMessage('Téléversement…'); try{const supabase=createClient(); const path=`${organizationId}/${student.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const {error:up}=await supabase.storage.from('student-documents').upload(path,file,{contentType:file.type,upsert:false}); if(up)throw up; const {data:row,error:db}=await supabase.from('student_documents').insert({organization_id:organizationId,student_id:student.id,file_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,title:file.name,category:'other'}).select('*').single(); if(db)throw db; setDocs(d=>[row,...d]);setMessage('Document ajouté avec succès.')}catch(e:any){setMessage(e?.message||'Erreur pendant le téléversement.')}finally{setBusy(false)}}
 async function openDocument(d:any){const supabase=createClient();const {data,error}=await supabase.storage.from('student-documents').createSignedUrl(d.file_path,300);if(error||!data?.signedUrl){setMessage('Impossible d’ouvrir ce document.');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 async function removeDocument(d:any){if(!confirm(`Supprimer ${d.file_name||d.title||'ce document'} ?`))return;setBusy(true);try{const supabase=createClient();const {error:s}=await supabase.storage.from('student-documents').remove([d.file_path]);if(s)throw s;const {error:db}=await supabase.from('student_documents').delete().eq('id',d.id).eq('organization_id',organizationId);if(db)throw db;setDocs(ds=>ds.filter(x=>x.id!==d.id));setMessage('Document supprimé.')}catch(e:any){setMessage(e?.message||'Suppression impossible.')}finally{setBusy(false)}}
 return <main className="student-dossier"><a className="back-link" href="/students">← Retour aux élèves</a><header className="student-dossier-header"><div className="dossier-identity"><div className="student-avatar-large">{initials}</div><div><p className="eyebrow">DOSSIER SCOLAIRE</p><h1>{student.first_name} {student.last_name}</h1><p><code>{student.student_number||'Matricule non renseigné'}</code> · <span className={`status status-${student.status}`}>{status}</span></p></div></div></header><nav className="student-tabs">{tabs.map(([key,label])=><button type="button" key={key} onClick={()=>setTab(key)} className={tab===key?'active':''}>{label}</button>)}</nav>
 {tab==='overview'&&<section className="dossier-panels"><article className="student-card"><h2>👤 Informations personnelles</h2><div className="dossier-details"><p><b>Nom complet</b>{student.first_name} {student.last_name}</p><p><b>Sexe</b>{student.sex==='M'?'Masculin':student.sex==='F'?'Féminin':'—'}</p><p><b>Date de naissance</b>{student.date_of_birth||'—'}</p><p><b>Adresse</b>{student.address||'—'}</p></div></article><article className="student-card"><h2>🎓 Scolarité</h2><div className="dossier-details"><p><b>Filière</b>{student.program_id||'—'}</p><p><b>Niveau</b>{student.level_id||'—'}</p><p><b>Année</b>{years.find(y=>y.id===student.academic_year_id)?.name||'—'}</p><p><b>Statut</b>{status}</p></div></article><article className="student-card"><h2>📞 Contacts</h2><div className="dossier-details"><p><b>Téléphone</b>{student.phone||'—'}</p><p><b>Email</b>{student.email||'—'}</p><p><b>Parent / tuteur</b>{student.parent_name||'—'}</p><p><b>Téléphone parent</b>{student.parent_phone||'—'}</p></div></article></section>}
 {tab==='documents'&&<section className="student-card"><div className="document-header"><div><h2>📄 Documents</h2><p>Pièces administratives et scolaires de l’élève.</p></div><input ref={input} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/><button type="button" className="primary-action" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Traitement…':'+ Ajouter un document'}</button></div>{message&&<div className="dossier-message">{message}</div>}{docs.length?<ul className="dossier-list">{docs.map(d=><li key={d.id}><span><b>{d.file_name||d.name||d.title||d.category||'Document'}</b><small>{d.category||'Document scolaire'}{d.mime_type?` · ${d.mime_type}`:''}{d.file_size?` · ${(d.file_size/1024/1024).toFixed(2)} Mo`:''}</small></span><span className="document-actions"><button type="button" onClick={()=>openDocument(d)}>Voir</button><button type="button" onClick={()=>removeDocument(d)} disabled={busy}>Supprimer</button></span></li>)}</ul>:<div className="dossier-empty"><strong>Aucun document enregistré</strong><span>Ajoutez un PDF ou une image depuis cet espace.</span></div>}</section>}
 {tab==='notes'&&<section className="student-card"><h2>📝 Notes</h2><div className="dossier-empty"><strong>Notes de l'élève</strong><span>Les notes saisies pour cet élève seront affichées ici dès que le module de résultats sera branché au dossier.</span></div></section>}{tab==='averages'&&<section className="student-card"><h2>📊 Moyennes</h2><div className="dossier-empty"><strong>Moyennes calculées</strong><span>Les moyennes par matière et la moyenne générale proviendront du moteur 4B.</span></div></section>}{tab==='bulletins'&&<section className="student-card"><h2>📑 Bulletins</h2><div className="dossier-empty"><strong>Bulletins de l'élève</strong><span>Les bulletins générés depuis le moteur 4C apparaîtront ici.</span></div></section>}{tab==='history'&&<section className="student-card"><h2>🕐 Historique scolaire</h2>{enrollments.length?<ul className="dossier-list">{enrollments.map(e=><li key={e.id}><span><b>{e.enrollment_number||'Inscription'}</b><small>{years.find(y=>y.id===e.academic_year_id)?.name||'Année non renseignée'} · {e.status}</small></span><small>{e.enrollment_date||''}</small></li>)}</ul>:<div className="dossier-empty"><strong>Aucune inscription enregistrée</strong></div>}</section>}</main>
}