'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function LicensingPage(){
 const supabase=createClient();
 const [data,setData]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data,error}=await supabase.rpc('get_billing_dashboard'); if(error)setError(error.message); else setData(data?.[0]??null); setLoading(false)})()},[]);
 const cards=data?[['Licences actives',data.active_licenses],['Expiration < 30 jours',data.expiring_30d],['Licences expirées',data.expired_licenses],['Établissements',data.institutions],['Commandes en attente',data.pending_orders],['Commandes payées',data.paid_orders],['Activations',data.activations],['CA encaissé',`${Number(data.total_paid||0).toLocaleString('fr-FR')} FCFA`]]:[];
 return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-7xl px-5 py-8"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="text-sm font-bold text-blue-600">← Administration</Link><h1 className="mt-2 text-3xl font-black">Licences & facturation</h1><p className="mt-1 text-sm text-slate-500">Vue de contrôle des abonnements CONIK et des activations desktop.</p></div><Link href="/activation" className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Tester une activation</Link></header>{loading?<div className="mt-10 rounded-2xl border bg-white p-8 text-slate-500">Chargement des indicateurs…</div>:error?<div className="mt-10 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900"><p className="font-bold">Accès au tableau de facturation</p><p className="mt-1 text-sm">{error}</p><p className="mt-3 text-sm">Connectez-vous avec un compte ayant le rôle administrateur ou super administrateur.</p></div>:<><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{String(value)}</p></div>)}</section><section className="mt-8 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-6 lg:col-span-2"><h2 className="font-bold">Flux commercial</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Commande</p><p className="mt-1 font-bold">Création → paiement</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Licence</p><p className="mt-1 font-bold">Clé → expiration</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Desktop</p><p className="mt-1 font-bold">Activation → sync</p></div></div></div><div className="rounded-2xl border bg-slate-900 p-6 text-white"><h2 className="font-bold">Sécurité</h2><ul className="mt-4 space-y-3 text-sm text-slate-300"><li>✓ Tables de facturation non exposées publiquement</li><li>✓ Activation via RPC sécurisé</li><li>✓ Journal des activations et émissions</li><li>✓ Période de grâce configurable</li></ul></div></section></>}</div></main>
}
